/* ------------------------------------------------------------------ */
/* Travel Visa Guides — Static data module                            */
/* Comprehensive visa guides for NRI travelers                        */
/* ------------------------------------------------------------------ */

export interface TravelVisaGuide {
  destination: string;
  slug: string;
  category: "europe" | "americas" | "asia" | "middle-east" | "oceania";
  overview: string;
  usCitizen: string;
  greenCard: string;
  h1b: string;
  indianPassport: string;
  consulates: string;
  applicationProcess: string;
  processingTimes: string;
  costs: string;
  tips: string;
  lastUpdated: string;
}

export const VISA_GUIDE_CATEGORIES = [
  { key: "europe", label: "Europe", emoji: "🇪🇺" },
  { key: "americas", label: "Americas", emoji: "🌎" },
  { key: "asia", label: "Asia", emoji: "🌏" },
  { key: "middle-east", label: "Middle East", emoji: "🏜️" },
  { key: "oceania", label: "Oceania", emoji: "🌊" },
] as const;

export const TRAVEL_VISA_GUIDES: TravelVisaGuide[] = [
  /* ================================================================ */
  /* EUROPE                                                           */
  /* ================================================================ */
  {
    destination: "Schengen Area (26 Countries)",
    slug: "schengen-visa",
    category: "europe",
    overview: `The Schengen visa is the single most important travel document for NRIs visiting Europe. One visa covers 26 countries: Austria, Belgium, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Italy, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Netherlands, Norway, Poland, Portugal, Slovakia, Slovenia, Spain, Sweden, and Switzerland.\n\nFor Indian passport holders — whether on H-1B, Green Card, or visiting from India — the Schengen visa process is the same application but with different supporting documents depending on your US immigration status.`,
    usCitizen: `## US Citizens — No Visa Required\n\nUS passport holders can enter the Schengen Area **visa-free for up to 90 days** within any 180-day period. Starting 2025, the **ETIAS** (European Travel Information and Authorization System) pre-travel authorization will be required.\n\n### ETIAS Details\n- **Cost**: €7 (~$8)\n- **Validity**: 3 years or until passport expires\n- **Processing**: Usually approved within minutes\n- **Application**: Online at [etias.com](https://www.etias.com)\n\n### What You Need\n- Valid US passport (at least 3 months beyond planned departure from Schengen)\n- Return/onward ticket\n- Proof of accommodation\n- Travel insurance recommended but not required\n\n### Key Rule: 90/180 Day Limit\nYou can stay a maximum of 90 days in ANY 180-day rolling period across ALL Schengen countries combined. Days in France + Italy + Germany all count toward the same 90.`,
    greenCard: `## Green Card Holders (Indian Passport)\n\n### You Still Need a Schengen Visa\nA US Green Card does **NOT** exempt Indian passport holders from the Schengen visa requirement. You must apply at a Schengen consulate.\n\n### Advantage of Having a Green Card\n- **Stronger application**: Consulates view GC holders more favorably — you have strong ties to the US\n- **Simpler financials**: US bank statements and tax returns are accepted readily\n- **Higher approval rate**: Near-certain approval with proper documentation\n\n### Required Documents\n1. **Passport**: Valid 3+ months beyond return date, with at least 2 blank pages\n2. **Green Card**: Copy (front and back)\n3. **DS-160/Visa application form**: Completed Schengen application form\n4. **Photos**: 2 recent passport-size photos (35mm x 45mm, white background)\n5. **Travel insurance**: Minimum €30,000 coverage, valid in all Schengen states\n6. **Flight itinerary**: Round-trip reservation\n7. **Hotel bookings**: For entire stay\n8. **Bank statements**: Last 3 months from US bank\n9. **Employment letter**: From US employer (if employed)\n10. **US tax returns**: Most recent year (Form 1040)\n11. **Cover letter**: Explaining purpose and itinerary\n\n### Which Consulate?\nApply at the consulate of the country where you'll spend the **most nights**. If equal, apply at the country of **first entry**.`,
    h1b: `## H-1B Visa Holders — The Tricky Scenario\n\nThis is where it gets complicated. As an H-1B holder, you're in the US on a temporary work visa, and Schengen consulates scrutinize your application more carefully.\n\n### Critical Requirements\n1. **Valid H-1B stamp in passport**: Your I-797 approval notice alone is NOT sufficient. You need a physical visa stamp. If your H-1B was approved via change of status (no stamp), you'll need to get stamped first — which means a US consulate visit in India or Canada.\n2. **Valid I-94**: Print from [i94.cbp.dhs.gov](https://i94.cbp.dhs.gov)\n3. **I-797 Approval Notice**: Copy of your current H-1B approval\n4. **Employment verification letter**: On company letterhead, stating:\n   - Your job title and salary\n   - H-1B validity dates\n   - Confirmation of approved leave dates\n   - Statement that position will be held\n\n### ⚠️ H-1B Transfer/Extension Pending?\nIf your H-1B transfer or extension is pending:\n- You can still apply, but include the receipt notice\n- Some consulates may ask for additional evidence\n- If your current H-1B expires while abroad, **you cannot re-enter the US** without a valid stamp\n\n### ⚠️ Advance Parole vs. H-1B Stamp\nIf you have an I-485 (green card application) pending:\n- **With Advance Parole (AP)**: You can travel on AP, but re-entering on AP may void your H-1B status. You'd re-enter as a "parolee."\n- **With valid H-1B stamp**: Enter on H-1B to maintain that status\n- **Best practice**: If you have both AP and H-1B stamp, enter on H-1B\n\n### Additional Documents for H-1B Holders\n- Last 3 pay stubs\n- W-2 from previous year\n- US bank statements (3 months)\n- Lease agreement or mortgage statement (proof of US residence)\n- Evidence of ties to US (car registration, utility bills, etc.)\n\n### Common Rejection Reasons for H-1B Holders\n- Insufficient proof of ties to the US\n- H-1B expiring within 3 months of return\n- No valid visa stamp in passport\n- Inadequate travel insurance\n- Inconsistent itinerary/booking details`,
    indianPassport: `## Indian Passport Holders (No US Status)\n\nFor family members visiting from India, the Schengen visa process requires more documentation and is processed through VFS Global centers.\n\n### Required Documents\n1. **Passport**: Valid 3+ months beyond return, 2 blank pages, issued within last 10 years\n2. **Application form**: Completed and signed\n3. **Photos**: 2 recent (35mm x 45mm, white background, taken within 6 months)\n4. **Travel insurance**: Min €30,000 coverage\n5. **Cover letter**: Purpose, itinerary, who you're visiting\n6. **Flight itinerary**: Round-trip booking\n7. **Hotel reservations**: Entire stay\n8. **Bank statements**: Last 6 months (Indian bank)\n9. **Income tax returns**: Last 3 years (ITR-V or IT acknowledgment)\n10. **Salary slips**: Last 3 months (if employed)\n11. **Company leave letter**: Approved leave dates\n12. **If visiting NRI family**:\n    - Invitation letter from family in US/Europe\n    - Host's passport + visa copy\n    - Host's bank statements\n    - Relationship proof\n\n### Sponsorship Letter\nIf an NRI family member is sponsoring the trip:\n- Notarized sponsorship letter\n- Sponsor's bank statements (3 months)\n- Sponsor's passport + US visa/GC copy\n- Proof of relationship (Aadhaar, ration card, etc.)\n\n### For Retired Persons\n- Pension certificate\n- Pension bank statements (6 months)\n- Property documents\n- Fixed deposit certificates`,
    consulates: `## Schengen Consulates in the USA\n\nAll Schengen visa applications in the US go through **VFS Global** (visa application centers), which forward to the respective consulate.\n\n### France (VFS Global)\n- **New York**: 290 Madison Avenue, 3rd Floor\n- **San Francisco**: 88 Kearny Street, Suite 600\n- **Washington DC**: 4101 Reservoir Road NW\n- **Chicago**: 205 N. Michigan Ave, Suite 3700\n- **Los Angeles**: 6300 Wilshire Blvd, Suite 1170\n- **Atlanta**: 3399 Peachtree Road NE, Suite 500\n- **Houston**: 3040 Post Oak Blvd, Suite 525\n- **Miami**: 1110 Brickell Avenue, Suite 210\n- Appointments: [france-visas.gouv.fr](https://france-visas.gouv.fr)\n\n### Germany (VFS Global)\n- **New York, SF, LA, Chicago, Houston, DC, Atlanta, Miami**\n- Appointments: [visa.vfsglobal.com/usa/en/deu](https://visa.vfsglobal.com/usa/en/deu)\n\n### Italy (VFS Global)\n- **Same cities as France**\n- Known for: Fastest processing in summer travel season\n- Appointments: [visa.vfsglobal.com/usa/en/ita](https://visa.vfsglobal.com/usa/en/ita)\n\n### Spain (BLS International)\n- **New York, SF, LA, Chicago, Houston, DC**\n- Uses BLS International instead of VFS\n- Appointments: [blsinternational.com/spain](https://blsinternational.com/spain)\n\n### Switzerland\n- **New York, SF, LA, Chicago, Houston, DC, Atlanta**\n- Appointments: [visa.vfsglobal.com/usa/en/che](https://visa.vfsglobal.com/usa/en/che)\n\n### Which Consulate to Choose?\n- Apply based on **jurisdiction** (your state of residence)\n- If your itinerary covers multiple Schengen countries, apply at the consulate of the country where you spend the **most nights**\n- If equal nights, apply at the **first country of entry**`,
    applicationProcess: `## Step-by-Step Application Process\n\n### Step 1: Determine Which Consulate\n- Country of longest stay, or first entry if equal\n- Check jurisdiction based on your US state of residence\n\n### Step 2: Create VFS Global Account\n- Go to the relevant VFS Global website for your destination country\n- Create an account and register\n\n### Step 3: Fill Out the Application Form\n- Complete the Schengen visa application form online\n- Form is the same for all 26 countries\n- Print and sign (2 signatures required — page 4 and page 5)\n\n### Step 4: Book VFS Appointment\n- **Book early** — appointments fill up fast, especially March-May for summer travel\n- Premium/priority appointments available for extra fee\n- Bring ALL documents to the appointment\n\n### Step 5: Attend Biometrics Appointment\n- Fingerprints + photo taken at VFS center\n- Must attend in person (no representatives)\n- Biometrics valid for 5 years — if done recently, may not need to repeat\n\n### Step 6: Submit Documents\n- Passport left with VFS (or courier option at some centers)\n- Pay visa fee + VFS service fee at the center\n- Collect receipt with tracking number\n\n### Step 7: Wait for Decision\n- Track status online via VFS\n- Passport returned via courier or pickup\n- If approved: visa sticker in passport with entry dates and allowed stay\n\n### Common Mistakes to Avoid\n- ❌ Booking non-refundable flights before visa is approved\n- ❌ Submitting blurry or old photos\n- ❌ Missing travel insurance (must explicitly cover Schengen area)\n- ❌ Inconsistent dates between cover letter, bookings, and application form\n- ❌ Not printing I-94 (for H-1B/GC holders in the US)\n- ❌ Forgetting to sign the application form`,
    processingTimes: `## Processing Times by Consulate\n\nProcessing times vary significantly by consulate and season:\n\n| Consulate | Standard | Peak (Apr-Jun) |\n|-----------|----------|----------------|\n| France SF | 10-15 days | 15-25 days |\n| France NYC | 12-18 days | 20-30 days |\n| Germany SF | 8-12 days | 15-20 days |\n| Germany NYC | 10-15 days | 18-25 days |\n| Italy NYC | 7-12 days | 15-20 days |\n| Spain NYC | 10-15 days | 15-25 days |\n| Switzerland SF | 8-12 days | 12-18 days |\n\n### Timeline Recommendation\n- **Apply 6-8 weeks before travel** during peak season (summer)\n- **Apply 4-6 weeks before** during off-peak\n- Applications open **6 months** before travel date\n- VFS appointments may need to be booked **2-4 weeks** in advance\n\n### Expedited Processing\n- Some consulates offer priority processing for additional fee\n- Not guaranteed — at consulate's discretion\n- Typically adds $50-80 to the cost`,
    costs: `## Visa Fees\n\n| Fee Type | Amount |\n|----------|--------|\n| Schengen visa fee (adult) | €80 (~$88) |\n| Schengen visa fee (child 6-12) | €40 (~$44) |\n| Children under 6 | Free |\n| VFS Global service fee | $35-45 |\n| Premium lounge (optional) | $50-60 |\n| Courier return (optional) | $25-35 |\n| Travel insurance (7 days) | $15-40 |\n| Travel insurance (15 days) | $25-60 |\n| Travel insurance (30 days) | $35-80 |\n| Passport photos | $10-15 |\n\n### Total Estimated Cost\n- **Budget**: ~$140-160 per person (visa + VFS + insurance)\n- **With premium/courier**: ~$200-250 per person\n\n### Payment\n- VFS accepts credit/debit cards and money orders\n- Cash NOT accepted at most US centers\n- Fee is **non-refundable** even if visa is denied`,
    tips: `## Pro Tips for NRIs\n\n### 🏆 Best Consulates (by speed + approval rate)\n1. **Italy NYC** — Often the fastest processing, friendly to Indian applicants\n2. **Germany SF** — Efficient, clear requirements, good for tech workers\n3. **France SF** — Reasonable times, but peak season gets backed up\n4. **Switzerland SF** — Small but efficient\n\n### 📅 Timing Tips\n- Book VFS appointments in **January-February** for summer travel\n- **Avoid applying in April-May** — that's when everyone applies for summer\n- Wednesday/Thursday appointments tend to have shorter wait times\n\n### 💡 Application Tips\n- Get a **multi-entry visa** — write "multiple entry" on your application form\n- If you've had a Schengen visa before, mention it — repeat applicants get longer validity\n- Cover letter should be detailed but not rambling — 1 page max\n- Print ALL hotel bookings (even if they're refundable — book.com free cancellation works)\n- Use **Booking.com or Hotels.com** with free cancellation for bookings you submit\n\n### 🛫 H-1B Specific Tips\n- If your H-1B expires within 6 months of travel, include a petition for extension/renewal\n- Get your employer letter on **official letterhead with HR contact info**\n- Include your **pay stubs** — they care about income stability\n- If you're being laid off or job-hunting, wait until you have stable employment\n\n### ⚠️ If Denied\n- You can **appeal** within 30 days\n- You can **reapply immediately** — no waiting period\n- Address the specific denial reason in your new application\n- Consider a different Schengen consulate (the one for your itinerary)`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "United Kingdom",
    slug: "uk-visa",
    category: "europe",
    overview: `The UK is NOT part of the Schengen Area, so you need a separate UK visa. The UK Standard Visitor Visa covers tourism, visiting family, and short business trips. The UK visa process is handled through VFS Global in the US.`,
    usCitizen: `## US Citizens — No Visa Required\n\nUS passport holders can enter the UK **visa-free for up to 6 months** as a Standard Visitor.\n\n### What You Need\n- Valid US passport\n- Return/onward ticket\n- Proof of accommodation\n- Evidence of sufficient funds\n\n### At the Border\n- Immigration officer may ask about purpose and length of stay\n- Have hotel booking and return flight details accessible\n- No stamp needed — electronic entry record`,
    greenCard: `## Green Card Holders (Indian Passport)\n\n### UK Visa Required\nIndian passport holders need a UK Standard Visitor Visa regardless of US Green Card status. However, having a US GC significantly strengthens your application.\n\n### Required Documents\n1. Valid Indian passport (6+ months validity)\n2. US Green Card (copy)\n3. UK visa application form (online)\n4. Biometrics appointment at VFS\n5. Bank statements (3 months, US bank)\n6. Employment letter or proof of income\n7. Hotel bookings and return flight\n8. Travel insurance (recommended)\n\n### Advantage\n- GC holders have very high approval rates\n- Shows strong ties to the US\n- Process is straightforward`,
    h1b: `## H-1B Visa Holders\n\n### UK Visa Required\nH-1B holders with Indian passports need a UK Standard Visitor Visa.\n\n### Key Requirements\n1. Valid Indian passport\n2. I-797 approval notice + valid H-1B stamp\n3. Valid I-94 printout\n4. Employment letter stating:\n   - Job title, salary, dates of employment\n   - H-1B validity period\n   - Approved leave for travel\n5. Last 3 pay stubs\n6. US bank statements (3 months)\n7. UK visa application form\n\n### ⚠️ Critical: Re-entry to US\n- Ensure your H-1B visa stamp hasn't expired\n- If stamp is expired but I-797 is valid, you'd need to get stamped at a US consulate before returning to the US\n- **Automatic visa revalidation** applies for UK trips under 30 days if returning to the same employer — check USCIS rules\n\n### Additional Documents\n- W-2 from previous year\n- Lease/mortgage proof\n- US utility bills (proof of residence)`,
    indianPassport: `## Indian Passport Holders (No US Status)\n\n### Standard Visitor Visa Required\nApply through VFS Global in India.\n\n### Required Documents\n1. Valid passport (6+ months, 2 blank pages)\n2. Online application form\n3. Biometrics at VFS India\n4. Bank statements (6 months)\n5. ITR for last 3 years\n6. Salary slips (3 months) or business proof\n7. Sponsorship letter (if sponsored by NRI family)\n8. Invitation letter from UK host\n9. Hotel bookings and flight itinerary\n10. Cover letter explaining purpose\n\n### If Visiting NRI Family\n- Host's UK visa/status proof\n- Host's bank statements\n- Relationship proof\n- Host's council tax bill or utility bill`,
    consulates: `## UK Visa Centers in the USA (VFS Global)\n\n- **New York**: 290 Madison Avenue\n- **San Francisco**: 88 Kearny Street\n- **Washington DC**: 3110 Fairview Park Drive\n- **Los Angeles**: 6300 Wilshire Blvd\n- **Chicago**: 625 N. Michigan Ave\n- **Houston**: 3040 Post Oak Blvd\n- **Atlanta**: 3399 Peachtree Road NE\n- **Miami**: 80 SW 8th Street\n\nAppointments: [visa.vfsglobal.com/usa/en/gbr](https://visa.vfsglobal.com/usa/en/gbr)`,
    applicationProcess: `## Application Steps\n\n1. **Apply online** at [gov.uk/standard-visitor](https://www.gov.uk/standard-visitor)\n2. **Pay visa fee** online\n3. **Book VFS appointment** for biometrics\n4. **Attend appointment** — fingerprints + photo + document submission\n5. **Wait for decision** — track online\n6. **Collect passport** via courier or pickup\n\n### Online Application Tips\n- Be honest about previous UK visa refusals\n- Clearly state dates and purpose\n- List ALL previous international travel (last 10 years)`,
    processingTimes: `## Processing Times\n\n| Service | Timeline | Cost |\n|---------|----------|------|\n| Standard | 3-4 weeks | Included in visa fee |\n| Priority | 5-7 business days | +£250 (~$320) |\n| Super Priority | 24 hours (next business day) | +£1,000 (~$1,280) |\n\n### Recommendation\n- Apply **4-6 weeks before travel**\n- Priority service worth it for last-minute trips\n- Super Priority available only at select centers`,
    costs: `## UK Visa Fees\n\n| Visa Type | Fee |\n|-----------|-----|\n| Standard Visitor (6 months) | £115 (~$148) |\n| Standard Visitor (2 years) | £400 (~$512) |\n| Standard Visitor (5 years) | £771 (~$988) |\n| Standard Visitor (10 years) | £963 (~$1,234) |\n| VFS service fee | ~$80 |\n| Priority processing | +£250 |\n| Super Priority | +£1,000 |\n\n### Pro Tip\nIf you travel to the UK frequently, the 2-year or 5-year visa is much better value.`,
    tips: `## Pro Tips\n\n- **Apply for 2-year visa** if you plan to visit again — the fee difference is worth it\n- UK uses a **points-based system** for immigrants but visitor visas are straightforward\n- **Automatic visa revalidation**: H-1B holders traveling to UK for under 30 days may be able to re-enter the US with an expired H-1B stamp (if I-797 is valid) — verify current USCIS guidance\n- **eGates**: UK eGates at airports are for UK/EU passports only — Indian passport holders must use the manned counter\n- **Keep all receipts and boarding passes** — useful if applying for future UK visas`,
    lastUpdated: "2026-05-24",
  },

  /* ================================================================ */
  /* AMERICAS                                                         */
  /* ================================================================ */
  {
    destination: "Mexico",
    slug: "mexico-visa",
    category: "americas",
    overview: `Mexico is one of the easiest international destinations for NRIs in the US. If you have a valid US visa or Green Card, you don't need a separate Mexican visa. This makes Cancún, Cabo, and other Mexican destinations incredibly popular weekend getaways for the Indian American community.`,
    usCitizen: `## US Citizens — No Visa Required\n\nUS passport holders can enter Mexico **visa-free for up to 180 days**.\n\n### What You Need\n- Valid US passport\n- FMM (Forma Migratoria Múltiple) — tourist card\n  - Filled out on the plane or at the border\n  - Free for air travelers (included in airfare)\n  - $35 fee for land crossings staying over 7 days\n- Return/onward ticket (sometimes asked)`,
    greenCard: `## Green Card Holders — No Visa Required!\n\n### The Best Part for NRIs\nIndian passport holders with a valid US Green Card can enter Mexico **visa-free for up to 180 days**.\n\n### What You Need\n- Valid Indian passport\n- Valid US Green Card (physical card)\n- FMM tourist card (filled on plane)\n\n### Important Notes\n- The Green Card must be valid (not expired)\n- Conditional Green Cards (2-year) work too\n- No need to apply for anything in advance`,
    h1b: `## H-1B Visa Holders — No Visa Required!\n\n### Great News\nIndian passport holders with a valid US visa (H-1B, L-1, F-1, etc.) can enter Mexico **visa-free for up to 180 days**.\n\n### What You Need\n- Valid Indian passport\n- Valid US visa stamp in passport (must not be expired)\n- Valid I-94\n- FMM tourist card\n\n### ⚠️ Critical Warnings\n- Your US visa stamp must be **currently valid** (not expired)\n- An I-797 approval notice alone is NOT sufficient — you need the physical visa stamp\n- If your H-1B stamp expired but was extended (I-797), you need a new stamp first\n\n### ⚠️ Re-entry to the US\n- **Automatic visa revalidation** applies for Mexico trips: if your H-1B stamp expired but I-797 is valid, AND your trip is under 30 days, AND you didn't apply for a new visa while in Mexico — you can re-enter the US\n- This is a major benefit of Mexico travel for H-1B holders with expired stamps\n- Always carry: passport, I-797, I-94 printout, employment letter`,
    indianPassport: `## Indian Passport Holders (No US Status)\n\n### Mexican Visa Required\nIndian passport holders without a valid US visa/GC need a Mexican visa.\n\n### Applying from India\n- Apply at Mexican Embassy in New Delhi or Consulate in Mumbai\n- Documents: passport, application form, photo, bank statements, flight booking, hotel reservation\n- Processing: 5-10 business days\n- Fee: ~$44\n\n### Required Documents\n1. Valid passport (6+ months)\n2. Completed application form\n3. Recent photo (white background)\n4. Bank statements (3 months)\n5. Employment letter or business proof\n6. Hotel and flight bookings\n7. Travel insurance recommended`,
    consulates: `## Mexican Consulates in the USA\n\nNRIs with valid US visas/GC don't need to visit a consulate — you're visa-free!\n\nFor Indian passport holders in the US without valid US status:\n- **Mexican Embassy**: 1911 Pennsylvania Ave NW, Washington DC\n- **Los Angeles**: 2401 W. 6th Street\n- **New York**: 27 East 39th Street\n- **San Francisco**: 532 Folsom Street\n- **Chicago**: 204 S. Ashland Ave\n- **Houston**: 4507 San Jacinto Street\n\nWebsite: [consulmex.sre.gob.mx](https://consulmex.sre.gob.mx)`,
    applicationProcess: `## For Those Who Need a Visa\n\n1. Schedule appointment at nearest Mexican consulate\n2. Complete application form online\n3. Gather required documents\n4. Attend appointment with originals + copies\n5. Pay fee\n6. Wait for processing (5-10 days)\n7. Collect passport with visa\n\n## For NRIs with US Visa/GC\nNo application needed! Just:\n1. Fill out FMM card on the plane\n2. Show passport + US visa/GC at immigration\n3. Get entry stamp\n4. Keep the FMM card — you'll need it when leaving`,
    processingTimes: `## Processing Times\n\n- **NRIs with US visa/GC**: No processing needed — instant entry\n- **From India (New Delhi)**: 5-10 business days\n- **From India (Mumbai)**: 7-12 business days\n- **From US (no valid US visa)**: 5-7 business days`,
    costs: `## Costs\n\n| Item | Cost |\n|------|------|\n| Mexican visa fee | ~$44 |\n| FMM tourist card (air) | Free (included in airfare) |\n| FMM tourist card (land, >7 days) | $35 |\n\n### For NRIs with US Visa/GC\nTotal cost: **$0** — no visa fees required!`,
    tips: `## Pro Tips for NRIs\n\n- **Weekend getaway**: Cancún and Cabo are 3-4 hour direct flights from most US cities\n- **H-1B auto revalidation**: Mexico is one of the best destinations for H-1B holders with expired stamps because of automatic visa revalidation\n- **Keep your FMM**: The small card you fill on the plane — you MUST return it when leaving Mexico. Lost FMM = $50 fine\n- **Carry multiple docs**: Even though visa-free, carry your I-797, I-94, and employment letter\n- **Currency**: ATMs in Mexico give the best exchange rate. Avoid airport exchange counters\n- **Safety**: Stick to tourist zones in Cancún, Cabo, Riviera Maya, Puerto Vallarta. Avoid traveling at night between cities`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Canada",
    slug: "canada-visa",
    category: "americas",
    overview: `Canada is a top destination for NRIs — whether visiting Niagara Falls, Vancouver, or the Canadian Rockies. US citizens need only an eTA, but Indian passport holders face different requirements depending on their US immigration status.`,
    usCitizen: `## US Citizens — eTA Required (Not a Visa)\n\nUS citizens can enter Canada **visa-free** but need an Electronic Travel Authorization (eTA) for air travel.\n\n### eTA Details\n- **Cost**: CAD $7 (~$5)\n- **Validity**: 5 years or until passport expires\n- **Processing**: Usually approved within minutes\n- **Apply online**: [canada.ca/eta](https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html)\n\n### Driving to Canada\n- No eTA needed for land crossings\n- Just bring your US passport\n- Enhanced Driver's License (EDL) also accepted at land borders from certain states`,
    greenCard: `## Green Card Holders (Indian Passport)\n\n### Visitor Visa Required\nIndian passport holders need a Canadian Visitor Visa (Temporary Resident Visa) even with a US Green Card.\n\n### Required Documents\n1. Valid Indian passport\n2. US Green Card (copy)\n3. Online application form (IMM 5257)\n4. Biometrics at VAC (Visa Application Centre)\n5. Digital photo meeting Canada specs\n6. Proof of funds (US bank statements)\n7. Travel itinerary\n8. Employment letter\n9. Purpose of visit letter\n\n### Processing\n- Online application at [ircc.canada.ca](https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html)\n- Biometrics at VFS/VAC center\n- Processing: 2-4 weeks (online)\n\n### Multiple Entry\n- Most GC holders get **multiple-entry visas** valid for up to 10 years\n- This means one application covers multiple trips`,
    h1b: `## H-1B Visa Holders\n\n### Visitor Visa Required\nH-1B holders with Indian passports need a Canadian Visitor Visa.\n\n### Key Requirements\n1. Valid Indian passport\n2. Valid H-1B stamp + I-797\n3. Valid I-94\n4. IMM 5257 application form\n5. Biometrics appointment\n6. Employment letter\n7. Pay stubs (3 months)\n8. US bank statements\n9. W-2\n\n### ⚠️ Re-entry to US\n- **Automatic visa revalidation** applies for Canada trips under 30 days\n- Same rules as Mexico — if H-1B stamp expired but I-797 valid, you can re-enter US from Canada\n- Carry all immigration documents\n\n### ⚠️ If H-1B Transfer Pending\n- You can still apply for Canada visa with receipt notice\n- But be careful about US re-entry if your old H-1B has expired`,
    indianPassport: `## Indian Passport Holders (No US Status)\n\n### Visitor Visa Required\nApply through VFS Global in India.\n\n### Required Documents\n1. Valid passport (6+ months)\n2. IMM 5257 application form\n3. Family information form (IMM 5645)\n4. Digital photo\n5. Biometrics at VFS India\n6. Bank statements (6 months)\n7. ITR (3 years)\n8. Employment proof\n9. Travel itinerary\n10. Letter of invitation (if visiting family)\n\n### Processing Time\n- Online from India: 4-8 weeks\n- Paper application: 6-12 weeks`,
    consulates: `## Canadian Visa Application Centres (VAC) in USA\n\nAll biometrics and document submission through VFS Global:\n- **New York**: 290 Madison Avenue\n- **Los Angeles**: 6300 Wilshire Blvd\n- **San Francisco**: Not available — use LA or apply online\n- **Washington DC**: 2828 Pennsylvania Ave NW (embassy)\n\nApply online: [ircc.canada.ca](https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html)`,
    applicationProcess: `## Application Steps\n\n1. **Create account** at [ircc.canada.ca](https://www.canada.ca/en/immigration-refugees-citizenship/services/application/account.html)\n2. **Complete online application** (IMM 5257)\n3. **Upload documents** digitally\n4. **Pay fee** online\n5. **Book biometrics** at nearest VAC/VFS center\n6. **Attend biometrics** (fingerprints + photo)\n7. **Submit passport** (if requested) via mail or in person\n8. **Receive decision** — usually 2-4 weeks`,
    processingTimes: `## Processing Times\n\n| Applicant Type | Timeline |\n|----------------|----------|\n| Online from US (GC/H-1B) | 2-4 weeks |\n| Online from India | 4-8 weeks |\n| Paper from India | 6-12 weeks |\n\nCheck current times: [ircc.canada.ca/processing-times](https://www.canada.ca/en/immigration-refugees-citizenship/services/application/check-processing-times.html)`,
    costs: `## Visa Fees\n\n| Fee | Amount |\n|-----|--------|\n| Visitor visa (single/multiple) | CAD $100 (~$75) |\n| Biometrics fee | CAD $85 (~$64) |\n| Family biometrics (max) | CAD $170 (~$128) |\n| VFS service fee | ~$40-50 |\n\n### Total: ~$180-190 per person`,
    tips: `## Pro Tips\n\n- **Apply online** — it's faster than paper\n- **Multiple-entry visa**: Always apply for multiple-entry — same fee, more flexibility\n- **Niagara Falls day trip**: If driving from Buffalo/NYC area, no visa needed for US citizens. GC/H-1B holders need Canadian visa even for a day trip\n- **H-1B auto revalidation**: Like Mexico, Canada trips under 30 days allow re-entry to US with expired H-1B stamp\n- **Nexus card**: If you travel to Canada often, apply for Nexus — expedited border crossing for US-Canada`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Costa Rica",
    slug: "costa-rica-visa",
    category: "americas",
    overview: `Costa Rica is a popular eco-tourism destination that's very accessible for NRIs. Indian passport holders with valid US, Canadian, or Schengen visas can enter visa-free.`,
    usCitizen: `## US Citizens — No Visa Required\n\nVisa-free entry for up to **90 days**.\n- Valid US passport required\n- Proof of onward travel\n- No advance registration needed`,
    greenCard: `## Green Card Holders — No Visa Required\n\nIndian passport holders with a valid US Green Card can enter Costa Rica **visa-free for up to 30 days**.\n- Carry both passport and GC\n- May be asked for return flight proof`,
    h1b: `## H-1B Holders — No Visa Required\n\nIndian passport holders with a valid US visa (H-1B, L-1, etc.) can enter Costa Rica **visa-free for up to 30 days**.\n\n### Requirements\n- Valid US visa stamp (not expired)\n- Valid Indian passport\n- Return flight proof\n\n### ⚠️ Note\n- The US visa must have at least 3 months validity remaining\n- I-797 alone is not sufficient — need the physical visa stamp`,
    indianPassport: `## Indian Passport (No US Status)\n\n### Costa Rica Visa Required\n- Apply at Costa Rica embassy/consulate\n- Or apply for a US/Canada/Schengen visa first (those exempt you)\n- Processing: 2-3 weeks\n- Documents: passport, bank statements, employment proof, itinerary`,
    consulates: `## Costa Rica Embassy in USA\n- **Washington DC**: 2114 S Street NW\n- Phone: (202) 499-2991\n- Website: [costarica-embassy.org](http://www.costarica-embassy.org)`,
    applicationProcess: `For NRIs with US visa/GC: No application needed.\nFor others: Apply at embassy with standard tourist visa documents.`,
    processingTimes: `- NRIs with US visa/GC: Instant (visa-free)\n- From India: 2-3 weeks\n- From US (no valid visa): 1-2 weeks`,
    costs: `| Item | Cost |\n|------|------|\n| Costa Rica visa | $30-50 |\n| NRIs with US visa/GC | Free |`,
    tips: `- **Great for H-1B holders**: Visa-free entry + auto revalidation for US re-entry\n- **Rainy season** (May-Nov) means fewer tourists and lower prices\n- **Exit tax** of $29 is usually included in your airfare\n- **Colones vs USD**: Many tourist areas accept USD but you'll get better rates with colones`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Colombia",
    slug: "colombia-visa",
    category: "americas",
    overview: `Colombia has become a trendy destination — Cartagena, Medellín, and Bogotá attract visitors worldwide. NRIs with US visas benefit from visa-free access.`,
    usCitizen: `## US Citizens — No Visa Required\nVisa-free for up to **90 days** (extendable to 180).\n- Valid US passport\n- Proof of onward travel`,
    greenCard: `## Green Card Holders — No Visa Required\nIndian passport + valid US GC = **visa-free for up to 90 days**.\n- Carry passport and Green Card\n- May need to show return ticket`,
    h1b: `## H-1B Holders — No Visa Required\nIndian passport + valid US visa = **visa-free for up to 90 days**.\n- Valid visa stamp required (not just I-797)\n- Carry employment letter and I-94`,
    indianPassport: `## Indian Passport (No US Status)\n### Visa Required\n- Apply online or at Colombian consulate\n- Documents: passport, photo, bank statements, itinerary\n- Processing: 5-15 business days\n- Fee: ~$52`,
    consulates: `## Colombian Consulates in USA\n- **New York**: 10 E 46th Street\n- **Houston**: 2400 Augusta Drive\n- **Miami**: 280 Aragon Ave, Coral Gables\n- **Los Angeles**: 8383 Wilshire Blvd`,
    applicationProcess: `NRIs with US visa/GC: No application needed.\nOthers: Apply online at [cancilleria.gov.co](https://www.cancilleria.gov.co)`,
    processingTimes: `- NRIs with US visa/GC: Instant\n- Online application: 5-15 business days`,
    costs: `| Item | Cost |\n|------|------|\n| Colombia visa | ~$52 |\n| NRIs with US visa/GC | Free |`,
    tips: `- **Cartagena**: Perfect 4-day weekend getaway from Miami/Houston\n- **Medellín**: Year-round spring weather, growing digital nomad scene\n- **Safety**: Stick to tourist areas, use registered taxis or Uber\n- **Cash**: Many places are cash-only. Withdraw from Bancolombia ATMs for lowest fees`,
    lastUpdated: "2026-05-24",
  },

  /* ================================================================ */
  /* ASIA                                                             */
  /* ================================================================ */
  {
    destination: "Thailand",
    slug: "thailand-visa",
    category: "asia",
    overview: `Thailand is one of the most popular destinations for Indian travelers — and increasingly for NRIs. As of 2024, Indian passport holders enjoy visa-free access for up to 60 days, making Thailand one of the easiest international trips.`,
    usCitizen: `## US Citizens — No Visa Required\nVisa-free for **30 days** (extendable by 30 days at immigration office).\n- Valid US passport\n- Return ticket\n- Thai immigration may ask for proof of accommodation`,
    greenCard: `## Green Card Holders — No Visa Required\nIndian passport holders enjoy **60-day visa-free access** to Thailand regardless of US status.\n- This is based on Indian passport — Thailand grants visa-free to Indians\n- Carry both passport and GC\n- Return ticket may be requested`,
    h1b: `## H-1B Holders — No Visa Required\nSame as above — Indian passport holders get **60-day visa-free** entry.\n- The Thailand visa exemption is based on citizenship, not US visa status\n- No additional documents needed beyond passport and return ticket\n- Thai Visa Exemption stamp given at airport`,
    indianPassport: `## Indian Passport (No US Status) — No Visa Required!\n\n### 60-Day Visa-Free Access\nAs of late 2024, Thailand grants Indian passport holders **visa-free entry for up to 60 days**.\n\n### What You Need\n- Valid passport (6+ months)\n- Return/onward ticket\n- Proof of accommodation\n- Proof of funds (~20,000 THB or ~$600 per person)\n\n### Extension\n- Can extend for 30 additional days at Thai immigration office (1,900 THB fee)\n- Total possible stay: 90 days`,
    consulates: `## Thai Consulates in USA\n- **Washington DC (Embassy)**: 1024 Wisconsin Ave NW\n- **New York**: 351 E 52nd Street\n- **Los Angeles**: 611 N. Larchmont Blvd\n- **Chicago**: 700 N. Rush Street\n\nFor visa-exempt travelers (most Indians): No consulate visit needed.`,
    applicationProcess: `## No Application Needed (Most Travelers)\n\nIndian passport holders entering visa-free:\n1. Arrive at Thai airport\n2. Fill out arrival card (on plane)\n3. Go to immigration counter\n4. Get 60-day stamp\n5. Done!\n\n## For Longer Stays (Tourist Visa)\nIf staying more than 60+30 days:\n- Apply for Tourist Visa at Thai consulate\n- Single entry: 60 days (extendable 30 more)\n- Multiple entry: 60 days per entry, valid 6 months`,
    processingTimes: `- Visa-free: Instant at airport\n- Tourist visa from US: 3-5 business days\n- Tourist visa from India: 3-5 business days`,
    costs: `| Item | Cost |\n|------|------|\n| Visa-free (up to 60 days) | Free |\n| Extension (30 days) | 1,900 THB (~$55) |\n| Tourist visa (single) | $40 |\n| Tourist visa (multiple) | $200 |`,
    tips: `## Pro Tips\n- **Visa-free is the way to go** — 60 days is plenty for vacation\n- **Bangkok tip**: Use BTS/MRT for transport, avoid tuk-tuks for long distances\n- **Best beaches**: Koh Samui, Krabi, Phuket (November to April)\n- **Indian food**: Bangkok has a huge Indian community — Little India on Sukhumvit Soi 3/1\n- **Digital payments**: Most tourist areas accept credit cards; street vendors need cash\n- **SIM card**: Buy at airport — AIS or TrueMove, ~300 THB for 15 days unlimited data`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Japan",
    slug: "japan-visa",
    category: "asia",
    overview: `Japan is a bucket-list destination for many NRIs. Cherry blossom season and the food alone make it worth the trip. Indian passport holders need a visa, but the process is straightforward.`,
    usCitizen: `## US Citizens — No Visa Required\nVisa-free for **90 days**.\n- Valid US passport\n- Return ticket\n- Visit Japan Web registration (customs declaration) recommended`,
    greenCard: `## Green Card Holders — Visa Required\nUS Green Card does NOT exempt Indian passport holders from Japanese visa requirement.\n\n### Required Documents\n1. Valid Indian passport (6+ months)\n2. Visa application form\n3. Photo (45mm x 45mm)\n4. Flight itinerary\n5. Hotel bookings\n6. US bank statements (3 months)\n7. Employment letter\n8. US Green Card copy\n9. Daily schedule/itinerary in Japan\n\n### Note\n- Japan requires a detailed day-by-day itinerary\n- Applications accepted at Japanese consulate (NOT VFS)`,
    h1b: `## H-1B Holders — Visa Required\nSame as GC holders — Japanese visa needed.\n\n### Additional Documents for H-1B\n- I-797 approval notice\n- Valid I-94\n- Pay stubs (3 months)\n- W-2\n- Employment letter with H-1B details\n\n### ⚠️ Processing Note\n- Japanese consulates in the US process applications in-house (not outsourced)\n- You may need to visit the consulate twice: once to submit, once to collect\n- Some consulates accept mail-in applications`,
    indianPassport: `## Indian Passport (No US Status)\n\n### Tourist Visa Required\nApply at Japanese Embassy/Consulate in India.\n\n### Required Documents\n1. Passport (6+ months, 2 blank pages)\n2. Visa application form\n3. Photo (45mm x 45mm, white background)\n4. Detailed daily itinerary\n5. Flight bookings\n6. Hotel reservations\n7. Bank statements (6 months)\n8. ITR (3 years)\n9. Employment proof\n10. Cover letter\n\n### Through Travel Agency\n- Japan often requires applications through approved travel agencies in India\n- Agencies: Cox & Kings, MakeMyTrip, Thomas Cook authorized for Japan visa`,
    consulates: `## Japanese Consulates in USA\n- **Washington DC (Embassy)**: 2520 Massachusetts Ave NW\n- **New York**: 299 Park Avenue, 18th Floor\n- **San Francisco**: 275 Battery Street, Suite 2100\n- **Los Angeles**: 350 S. Grand Ave, Suite 1700\n- **Chicago**: 737 N. Michigan Ave, Suite 1000\n- **Houston**: 909 Fannin Street, Suite 3000\n- **Atlanta**: 3438 Peachtree Road NE\n- **Boston**: 600 Atlantic Avenue\n- **Seattle**: 601 Union Street, Suite 500\n\nWebsite: [us.emb-japan.go.jp](https://www.us.emb-japan.go.jp)`,
    applicationProcess: `## Application Steps\n\n1. **Determine jurisdiction** based on your state of residence\n2. **Download application form** from consulate website\n3. **Prepare detailed itinerary** — Japan requires day-by-day plans\n4. **Gather documents** including financial proof\n5. **Submit at consulate** (in person or by mail, depending on consulate)\n6. **Wait for processing** (5-7 business days)\n7. **Collect passport** (in person or prepaid return envelope)\n\n### Important: Day-by-Day Itinerary\nJapan is unique in requiring a detailed schedule:\n- Date, city, activities planned, hotel name for each day\n- Include addresses and phone numbers of hotels\n- Be specific: "April 15: Arrive Tokyo Narita, check in Hotel Gracery Shinjuku, explore Shinjuku area"`,
    processingTimes: `## Processing Times\n\n| From | Timeline |\n|------|----------|\n| US (consulate) | 5-7 business days |\n| India (embassy) | 5-7 business days |\n| India (through agency) | 7-10 business days |\n\n### Note\n- No expedited processing available\n- Apply at least 3-4 weeks before travel\n- Cherry blossom season (March-April) may have longer processing`,
    costs: `| Item | Cost |\n|------|------|\n| Single-entry visa | Free (for Indian passport) |\n| Multiple-entry visa | Free (for Indian passport) |\n| Transit visa | Free |\n\n### Japan Waives Fees for Indian Nationals\nJapan does not charge visa fees for Indian passport holders — one of the few countries to do this!`,
    tips: `## Pro Tips\n\n- **Free visa!** Japan doesn't charge Indians for visas — take advantage\n- **JR Pass**: Buy the Japan Rail Pass before you go — unlimited bullet train travel. Get the 7-day or 14-day pass\n- **Cherry blossoms**: Last week of March through mid-April in Tokyo, slightly later in northern Japan\n- **Cash society**: Japan is still very cash-dependent. Carry yen. 7-Eleven ATMs accept international cards\n- **IC Card**: Get a Suica or Pasmo card at the airport for trains and convenience stores\n- **Vegetarian-friendly**: Tell restaurants "bejitarian" or show a card. Many Buddhist temples serve shojin ryori (temple cuisine)\n- **Pocket WiFi**: Rent at airport — much better than international roaming`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Singapore",
    slug: "singapore-visa",
    category: "asia",
    overview: `Singapore is a popular stopover for NRIs traveling to India and a destination in its own right. Indian passport holders need a visa, but the process has been streamlined with an e-visa system.`,
    usCitizen: `## US Citizens — No Visa Required\nVisa-free for **90 days**.\n- Valid US passport\n- Arrival card filed online (SG Arrival Card via ICA website)`,
    greenCard: `## Green Card Holders — Visa Required\nIndian passport holders need a Singapore visa regardless of US GC status.\n\n### Process\n- Apply online through authorized visa agent or Singapore consulate\n- GC status strengthens application\n- Multiple-entry visas often granted`,
    h1b: `## H-1B Holders — Visa Required\nSame as GC holders — Singapore visa needed.\n\n### Transit Without Visa (TWOV)\nIf you're only transiting through Changi Airport (not leaving the airport):\n- No visa needed for transit\n- Must have confirmed onward ticket within 24 hours\n- Can access transit area lounges and shops`,
    indianPassport: `## Indian Passport (No US Status)\n\n### e-Visa Required\n- Apply online through authorized agents in India\n- Processing: 3-5 business days\n- Multiple-entry visas available\n\n### Documents\n1. Passport (6+ months)\n2. Online application\n3. Photo (digital)\n4. Bank statements (3 months)\n5. Employment proof\n6. Cover letter\n7. Hotel and flight bookings`,
    consulates: `## Singapore Consulates\n- **Washington DC (Embassy)**: 3501 International Place NW\n- **New York**: 231 E 51st Street\n- **San Francisco**: 595 Market Street, Suite 2450\n\n### Authorized Visa Agents (from India)\n- VFS Global\n- BLS International\n- Cox & Kings`,
    applicationProcess: `1. Apply online or through authorized agent\n2. Upload documents and photo\n3. Pay fee online\n4. Receive e-visa via email (3-5 days)\n5. Print e-visa and carry with passport`,
    processingTimes: `- e-Visa: 3-5 business days\n- From US consulate: 3-5 business days\n- Express (if available): 1-2 business days`,
    costs: `| Item | Cost |\n|------|------|\n| e-Visa | SGD $30 (~$22) |\n| Agent processing fee | $15-25 |\n| Multiple-entry (63 days) | SGD $30 |`,
    tips: `- **Changi Airport transit**: No visa needed if you don't leave the airport\n- **Hawker centers**: Best food at lowest prices. Try Maxwell Food Centre and Lau Pa Sat\n- **EZ-Link card**: Like a metro card — use for MRT and buses\n- **Fine city**: Singapore is strict — no gum, no jaywalking, no eating on MRT. Seriously.\n- **Gardens by the Bay**: Free outdoor areas; paid for Cloud Forest and Flower Dome (worth it)\n- **Weekend in Singapore**: 3 days is perfect for a first visit`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Bali / Indonesia",
    slug: "indonesia-visa",
    category: "asia",
    overview: `Bali is the dream vacation for many NRIs — affordable luxury, stunning beaches, rice terraces, and Hindu temples that feel like a spiritual home for Indian visitors. Indian passport holders get visa-free access.`,
    usCitizen: `## US Citizens — Visa-Free or VOA\n- **Visa-free**: 30 days (non-extendable)\n- **Visa on Arrival**: 30 days (extendable once for 30 more days) — $35 at airport\n- Get VOA if you might want to extend`,
    greenCard: `## Green Card Holders — Visa-Free!\nIndian passport holders can enter Indonesia **visa-free for 30 days**.\n- This is based on Indian citizenship — Indonesia grants visa-free to Indians\n- Or get VOA ($35) for extendable 30 days`,
    h1b: `## H-1B Holders — Visa-Free!\nSame — Indian passport = **visa-free for 30 days** in Indonesia.\n- US visa status doesn't matter\n- Get VOA ($35) if you want the option to extend`,
    indianPassport: `## Indian Passport — Visa-Free!\n\n### 30-Day Visa-Free Access\nIndonesia grants Indian passport holders visa-free entry for tourism.\n\n### Options at Airport\n1. **Visa-Free**: 30 days, non-extendable, free\n2. **Visa on Arrival**: 30 days, extendable 30 more, $35\n\n### Choose VOA If:\n- You might want to stay longer than 30 days\n- You want flexibility\n\n### What You Need\n- Passport valid 6+ months\n- Return/onward ticket\n- Proof of accommodation`,
    consulates: `## Indonesian Consulates in USA\n- **Washington DC**: 2020 Massachusetts Ave NW\n- **New York**: 5 E 68th Street\n- **Los Angeles**: 3457 Wilshire Blvd\n- **San Francisco**: 1111 Columbus Avenue\n- **Houston**: 10900 Richmond Ave\n- **Chicago**: 211 W. Wacker Drive`,
    applicationProcess: `No visa application needed for most travelers! At the airport:\n1. Choose Visa-Free or VOA lane at immigration\n2. For VOA: pay $35 (cash USD or card)\n3. Get stamp in passport\n4. Done!`,
    processingTimes: `- At airport: Instant (visa-free or VOA)\n- VOA extension: 2-3 business days at immigration office in Bali`,
    costs: `| Item | Cost |\n|------|------|\n| Visa-free (30 days) | Free |\n| VOA (30 days, extendable) | $35 |\n| VOA extension (30 days) | 500,000 IDR (~$32) |`,
    tips: `- **Get VOA**: Even if staying under 30 days, the $35 VOA gives you flexibility\n- **Temples**: Bali's Hindu temples feel familiar to Indian visitors — Tanah Lot, Uluwatu, Besakih\n- **Ubud vs beaches**: Ubud for culture/rice terraces, Seminyak for beaches/nightlife, Nusa Dua for families\n- **Scooter rental**: ~$5/day but get international driving permit. Traffic is chaotic.\n- **Money changers**: Use bank-affiliated money changers. Avoid street changers offering "no commission"\n- **Vegetarian paradise**: Bali has excellent vegetarian/vegan restaurants — search "warung" + "vegetarian"`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Vietnam",
    slug: "vietnam-visa",
    category: "asia",
    overview: `Vietnam is rapidly becoming a top destination for Indian travelers — Ha Long Bay, Hanoi's street food, and Ho Chi Minh City's energy make it an incredible trip. e-Visa makes entry straightforward.`,
    usCitizen: `## US Citizens — e-Visa or Visa-Free\n- **e-Visa**: Up to 90 days, single or multiple entry\n- Apply online at [evisa.xuatnhapcanh.gov.vn](https://evisa.xuatnhapcanh.gov.vn)\n- Processing: 3 working days\n- Cost: $25`,
    greenCard: `## Green Card Holders — e-Visa Required\nIndian passport holders need a Vietnam e-Visa regardless of US status.\n- Apply online — quick and easy\n- GC status doesn't affect the process (it's based on passport)`,
    h1b: `## H-1B Holders — e-Visa Required\nSame as GC holders — apply for Vietnam e-Visa online.\n- Based on Indian passport, not US visa\n- Simple online process`,
    indianPassport: `## Indian Passport — e-Visa Required\n\n### Apply Online\n- Website: [evisa.xuatnhapcanh.gov.vn](https://evisa.xuatnhapcanh.gov.vn)\n- **Cost**: $25\n- **Processing**: 3 working days\n- **Validity**: Up to 90 days, single or multiple entry\n\n### Documents for e-Visa\n1. Passport scan (bio page)\n2. Digital photo (4x6cm, white background)\n3. Credit/debit card for payment\n\n### At Airport\n- Print your e-Visa approval letter\n- Show at immigration with passport\n- Get entry stamp`,
    consulates: `## Vietnamese Consulates in USA\n- **Washington DC (Embassy)**: 1233 20th Street NW\n- **New York**: 866 UN Plaza\n- **San Francisco**: 1700 California Street\n- **Houston**: 5251 Westheimer Road\n\nBut e-Visa is the way to go — no consulate visit needed.`,
    applicationProcess: `1. Go to [evisa.xuatnhapcanh.gov.vn](https://evisa.xuatnhapcanh.gov.vn)\n2. Fill online form\n3. Upload passport photo and personal photo\n4. Pay $25\n5. Receive e-Visa by email in 3 working days\n6. Print and carry with passport`,
    processingTimes: `- e-Visa: 3 working days\n- Apply at least 1 week before travel (buffer for delays)`,
    costs: `| Item | Cost |\n|------|------|\n| e-Visa (single entry, 30 days) | $25 |\n| e-Visa (multiple entry, 90 days) | $50 |`,
    tips: `- **e-Visa only**: Don't use third-party visa services — they charge $50-80 for the same thing. Use the official government website.\n- **Cash is king**: Vietnam is very cash-oriented. ATMs dispense VND (Vietnamese dong). Vietcombank and BIDV ATMs have lowest fees\n- **Street food**: Hanoi's phở and bánh mì are legendary. Eat where locals eat.\n- **Ha Long Bay**: Book 2-day/1-night cruise for the best experience\n- **Grab**: Vietnam's Uber equivalent — use for taxis and motorbike rides\n- **SIM card**: Buy at airport — Viettel or Mobifone, ~$5 for 30 days data`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Sri Lanka",
    slug: "sri-lanka-visa",
    category: "asia",
    overview: `Sri Lanka is a short flight from India and offers incredible value — ancient ruins, tea country, wildlife, and beautiful beaches. The ETA (Electronic Travel Authorization) makes entry simple.`,
    usCitizen: `## US Citizens — ETA Required\n- Apply online before travel\n- 30 days, extendable to 90\n- Cost: $50\n- Apply: [eta.gov.lk](https://www.eta.gov.lk)`,
    greenCard: `## Green Card Holders — ETA Required\nSame process as any Indian passport holder — apply for ETA online.\n- US GC doesn't change the process\n- $50, processed in 24-48 hours`,
    h1b: `## H-1B Holders — ETA Required\nSame — apply for ETA online.\n- Based on passport nationality\n- Quick online process`,
    indianPassport: `## Indian Passport — ETA Required\n\n### Online Application\n- Website: [eta.gov.lk](https://www.eta.gov.lk)\n- Cost: $50 (or free during promotional periods)\n- Processing: 24-48 hours\n- Validity: 30 days, extendable to 90\n\n### Documents\n- Valid passport\n- Credit card for payment\n- Travel dates and hotel info`,
    consulates: `## Sri Lankan Consulates\n- **Washington DC (Embassy)**: 3025 Whitehaven Street NW\n- **New York**: 820 Second Avenue\n- **Los Angeles**: 3250 Wilshire Blvd\n\nBut ETA online is recommended over consulate visit.`,
    applicationProcess: `1. Go to [eta.gov.lk](https://www.eta.gov.lk)\n2. Select "Tourist ETA"\n3. Fill form with passport and travel details\n4. Pay online\n5. Receive ETA via email (24-48 hours)\n6. Print and carry`,
    processingTimes: `- ETA online: 24-48 hours\n- At airport (not recommended): May face delays`,
    costs: `| Item | Cost |\n|------|------|\n| ETA (tourist) | $50 |\n| Extension (up to 90 days) | $50 |\n| Children under 12 | Free |`,
    tips: `- **Apply ETA online before travel** — don't rely on airport\n- **Train rides**: The Kandy-Ella train is one of the most scenic in the world. Book First Class\n- **Sigiriya**: The Lion Rock fortress is a must-visit. Go early morning to avoid heat\n- **Food**: Sri Lankan cuisine is similar to South Indian — rice and curry, hoppers, kottu roti\n- **Tuk-tuks**: Negotiate price before getting in. PickMe app is like Uber for tuk-tuks`,
    lastUpdated: "2026-05-24",
  },

  /* ================================================================ */
  /* MIDDLE EAST                                                      */
  /* ================================================================ */
  {
    destination: "UAE (Dubai & Abu Dhabi)",
    slug: "uae-visa",
    category: "middle-east",
    overview: `Dubai and Abu Dhabi are major layover destinations and vacation spots for NRIs. The UAE offers visa-on-arrival for many passport holders, and Indian passport holders can get e-visas or transit visas easily.`,
    usCitizen: `## US Citizens — Visa-Free\nVisa-free for **30 days** (extendable).\n- Valid US passport\n- Stamp at airport immigration\n- Can extend for additional 30 days ($70)`,
    greenCard: `## Green Card Holders — Visa on Arrival\nIndian passport holders with US Green Cards can get **visa on arrival for 14 days** in the UAE.\n\n### Alternative: Pre-approved e-Visa\n- Apply through airlines (Emirates, Etihad) or online\n- 30 days validity\n- More convenient than VOA`,
    h1b: `## H-1B Holders — e-Visa or Transit Visa\n\n### For Tourism (14+ days)\n- Apply for UAE e-Visa online\n- Or through Emirates/Etihad (if flying with them)\n- 30-day tourist visa\n\n### For Transit (48-96 hours)\n- **Emirates/flydubai passengers**: Free 48-hour transit visa\n- **Etihad passengers**: Free 48-hour transit visa through Abu Dhabi\n- Apply through airline's website before travel\n\n### Note\n- H-1B holders may be eligible for VOA depending on current UAE policy\n- Check latest rules at [icp.gov.ae](https://icp.gov.ae)`,
    indianPassport: `## Indian Passport (No US Status)\n\n### Options\n1. **e-Visa (tourist)**: Apply online, 30 days, ~$80-100\n2. **Transit visa (48h)**: Free through Emirates/Etihad\n3. **Through hotel/airline**: Many UAE hotels and airlines can sponsor visas\n\n### Documents for e-Visa\n- Passport (6+ months validity)\n- Photo\n- Bank statement\n- Return ticket\n- Hotel booking`,
    consulates: `## UAE Consulates in USA\n- **Washington DC (Embassy)**: 3522 International Court NW\n- **New York**: 2 Dag Hammarskjöld Plaza\n- **Los Angeles**: 10866 Wilshire Blvd\n- **Houston**: 8 Greenway Plaza\n\nBut e-visa/online is recommended.`,
    applicationProcess: `### e-Visa (Recommended)\n1. Apply at [icp.gov.ae](https://icp.gov.ae) or through airline (Emirates)\n2. Upload passport copy and photo\n3. Pay online\n4. Receive e-visa via email (3-5 days)\n5. Print and carry\n\n### Through Airlines\n- Emirates: Apply during booking or through emirates.com\n- Etihad: Apply through etihadairways.com\n- Often processed in 3-4 days`,
    processingTimes: `- e-Visa: 3-5 business days\n- Through airline: 3-4 days\n- Express: 24 hours (additional fee)`,
    costs: `| Item | Cost |\n|------|------|\n| 30-day tourist e-Visa | ~$80-100 |\n| 14-day transit visa (through airline) | Free-$30 |\n| 48-hour transit visa | Free (through airline) |\n| 90-day visit visa | ~$220-270 |`,
    tips: `- **Dubai stopover**: If transiting through Dubai on Emirates, take advantage of the free/cheap transit visa for a 48-hour Dubai experience\n- **Summer heat**: Avoid June-August — temperatures hit 45-50°C. Best time: November-March\n- **Metro**: Dubai Metro is clean, cheap, and connects key tourist spots\n- **Friday brunch**: A Dubai institution — unlimited food and drinks at top hotels ($50-150)\n- **Gold Souk**: Great for gold jewelry purchases. Prices are competitive.\n- **Alcohol**: Available at licensed venues (hotels, restaurants). Not in public.\n- **Dress code**: Modest clothing in malls and public areas. Beachwear only at beaches/pools.`,
    lastUpdated: "2026-05-24",
  },

  /* ================================================================ */
  /* OCEANIA                                                          */
  /* ================================================================ */
  {
    destination: "Australia",
    slug: "australia-visa",
    category: "oceania",
    overview: `Australia requires a visa for Indian passport holders, but the online e-Visa (subclass 600) process is well-established. Great Barrier Reef, Sydney Opera House, and Melbourne's food scene make it worth the effort.`,
    usCitizen: `## US Citizens — eTA (subclass 601)\n- Apply online via the Australian ETA app\n- **Cost**: AUD $20 (~$13)\n- **Validity**: 12 months, multiple entries, 90 days per visit\n- Approved within minutes/hours`,
    greenCard: `## Green Card Holders — Visitor Visa (subclass 600)\nIndian passport holders need a full visitor visa.\n\n### Online Application\n- Apply at [immi.homeaffairs.gov.au](https://immi.homeaffairs.gov.au)\n- Upload all documents digitally\n- No biometrics usually required from US\n\n### Documents\n1. Valid passport\n2. US Green Card copy\n3. Bank statements (3 months)\n4. Employment letter\n5. Travel itinerary\n6. Health insurance\n7. Evidence of ties to US/India`,
    h1b: `## H-1B Holders — Visitor Visa (subclass 600)\nSame as GC holders — full visitor visa required.\n\n### Additional Documents\n- I-797 + valid I-94\n- H-1B details in employment letter\n- Evidence of US residence (lease, bills)\n- Proof of ties and intent to return to US`,
    indianPassport: `## Indian Passport — Visitor Visa (subclass 600)\n\n### Online Application\n- Apply at [immi.homeaffairs.gov.au](https://immi.homeaffairs.gov.au)\n- Create ImmiAccount\n- Upload documents\n\n### Documents from India\n1. Valid passport\n2. Bank statements (6 months)\n3. ITR (3 years)\n4. Employment proof\n5. Property documents\n6. Family ties proof\n7. Health insurance\n8. Invitation letter (if visiting family)`,
    consulates: `## Australian Consulates in USA\n- **Washington DC (Embassy)**: 1601 Massachusetts Ave NW\n- **New York**: 150 E 42nd Street\n- **San Francisco**: 575 Market Street\n- **Los Angeles**: 2029 Century Park East\n- **Houston**: 3009 Post Oak Blvd\n- **Chicago**: 123 N. Wacker Drive\n\nBut online application is standard — no consulate visit needed.`,
    applicationProcess: `1. Create ImmiAccount at [immi.homeaffairs.gov.au](https://immi.homeaffairs.gov.au)\n2. Select "Visitor visa (subclass 600)"\n3. Fill application form online\n4. Upload all documents (scans/photos)\n5. Pay fee online\n6. Wait for decision (visa granted electronically)\n7. No stamp needed — visa is linked to passport number digitally`,
    processingTimes: `| From | Timeline |\n|------|----------|\n| From US | 2-4 weeks |\n| From India | 4-8 weeks |\n| Peak season (Dec-Feb) | May be longer |\n\nCheck current times: [immi.homeaffairs.gov.au](https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-processing-times)`,
    costs: `| Item | Cost |\n|------|------|\n| Visitor visa (subclass 600) | AUD $190 (~$125) |\n| Biometrics (if required) | AUD $85 (~$56) |\n\n### No Refund Policy\nFee is non-refundable even if denied.`,
    tips: `- **Apply early**: Australian visa processing can be slow — apply 6-8 weeks before travel\n- **Digital visa**: No sticker in passport — visa is electronic. Check status via VEVO\n- **SIM card**: Get an Optus or Vodafone prepaid SIM at the airport\n- **Driving**: International Driving Permit (IDP) accepted. Drive on the left (like India!)\n- **Tipping**: Not expected in Australia\n- **Health insurance**: Medicare doesn't cover tourists. Buy travel insurance.\n- **Best time**: September-November (spring) or March-May (autumn). Avoid summer (Dec-Feb) heat in inland areas.`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "New Zealand",
    slug: "new-zealand-visa",
    category: "oceania",
    overview: `New Zealand is a once-in-a-lifetime destination — from Milford Sound to Hobbiton to Queenstown's adventure sports. Indian passport holders need an NZeTA or visitor visa depending on status.`,
    usCitizen: `## US Citizens — NZeTA Required\n- **NZeTA** (New Zealand Electronic Travel Authority)\n- Apply via app or online\n- Cost: NZD $17-23 (~$10-15)\n- Plus International Visitor Conservation and Tourism Levy (IVL): NZD $100 (~$62)\n- Valid 2 years`,
    greenCard: `## Green Card Holders — Visitor Visa Required\nIndian passport holders need a New Zealand Visitor Visa.\n\n### Apply Online\n- [immigration.govt.nz](https://www.immigration.govt.nz)\n- Documents similar to Australia visitor visa\n- GC status strengthens application`,
    h1b: `## H-1B Holders — Visitor Visa Required\nSame as GC holders — visitor visa needed.\n- Apply online\n- Include H-1B documentation\n- 2-4 weeks processing`,
    indianPassport: `## Indian Passport — Visitor Visa Required\n\n### Online Application\n- [immigration.govt.nz](https://www.immigration.govt.nz)\n- Create RealMe account\n- Upload documents\n\n### Documents\n1. Valid passport\n2. Bank statements\n3. Employment proof\n4. Itinerary and bookings\n5. Health insurance\n6. Character documents (police clearance if staying 24+ months)`,
    consulates: `## New Zealand Consulates\n- **Washington DC (Embassy)**: 37 Observatory Circle NW\n- **New York**: No consulate — use DC or apply online\n- **Los Angeles**: 2425 Olympic Blvd\n\nOnline application is standard.`,
    applicationProcess: `1. Go to [immigration.govt.nz](https://www.immigration.govt.nz)\n2. Create account\n3. Apply for Visitor Visa\n4. Upload documents\n5. Pay fee\n6. Wait for electronic decision`,
    processingTimes: `- From US: 2-4 weeks\n- From India: 4-6 weeks\n- Apply 6+ weeks before travel`,
    costs: `| Item | Cost |\n|------|------|\n| Visitor visa | NZD $246 (~$152) |\n| IVL levy | NZD $100 (~$62) |\n| Total | ~$215 |`,
    tips: `- **Campervan trip**: The best way to see NZ. Rent from Jucy or Mighty Campers\n- **Milford Sound**: Book the day cruise — it's unforgettable\n- **Queenstown**: Bungee jumping, skydiving, jet boats — adventure capital of the world\n- **Hobbiton**: Book official tour from Matamata — Tolkien fans will love it\n- **Driving**: Left-hand traffic (like India). Roads are excellent but winding\n- **Wifi**: Cell coverage is spotty outside cities. Download offline maps\n- **Best time**: December-February (NZ summer). April-May for autumn colors.`,
    lastUpdated: "2026-05-24",
  },

  /* ================================================================ */
  /* MORE AMERICAS                                                    */
  /* ================================================================ */
  {
    destination: "Brazil",
    slug: "brazil-visa",
    category: "americas",
    overview: `Brazil waived visa requirements for several nationalities in recent years. Indian passport holders still need a visa, but the process has been simplified with an e-visa.`,
    usCitizen: `## US Citizens — e-Visa Required\n- Apply at [gov.br/mre](https://www.gov.br/mre)\n- Cost: $80\n- Validity: 5 years, multiple entry, 90 days per visit\n- Processing: 5-10 days`,
    greenCard: `## Green Card Holders — Visa Required\nIndian passport holders need a Brazil visa regardless of GC status.\n- Apply online for e-visa\n- Process same as Indian passport holders`,
    h1b: `## H-1B Holders — Visa Required\nSame — Brazil visa needed based on Indian passport.\n- e-Visa available online\n- Include US employment documentation`,
    indianPassport: `## Indian Passport — e-Visa\n\n### Apply Online\n- [gov.br/mre/en](https://www.gov.br/mre/en)\n- Cost: $80\n- Processing: 5-10 business days\n- Validity: up to 5 years\n\n### Documents\n1. Passport photo page scan\n2. Digital photo\n3. Credit card\n4. Travel itinerary (not required to submit)`,
    consulates: `## Brazilian Consulates in USA\n- **Washington DC**: 3006 Massachusetts Ave NW\n- **New York**: 225 E 41st Street\n- **San Francisco**: 300 Montgomery Street\n- **Miami**: 80 SW 8th Street\n- **Los Angeles**: 8484 Wilshire Blvd\n- **Houston**: 1233 West Loop South`,
    applicationProcess: `1. Apply online at [gov.br/mre](https://www.gov.br/mre)\n2. Upload photo and passport scan\n3. Pay $80\n4. Receive e-visa via email (5-10 days)\n5. Print and carry`,
    processingTimes: `- e-Visa: 5-10 business days\n- Apply 2-3 weeks before travel`,
    costs: `| Item | Cost |\n|------|------|\n| e-Visa | $80 |\n| Multiple entry, 5-year validity | Included |`,
    tips: `- **Carnival**: February — plan 6+ months ahead for Rio\n- **Safety**: Be vigilant in Rio and São Paulo. Use registered taxis. Don't flash expensive items.\n- **Iguazu Falls**: Brazilian AND Argentinian sides are worth seeing\n- **Cash vs card**: Major cities accept cards widely. Smaller towns need cash (reais)\n- **Portuguese**: Very few people speak English. Learn basics or use Google Translate`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Caribbean Islands",
    slug: "caribbean-visa",
    category: "americas",
    overview: `The Caribbean offers diverse options for NRIs — from visa-free islands (with US visa) to luxury all-inclusive resorts. Here's a roundup of major Caribbean destinations.`,
    usCitizen: `## US Citizens — Generally Visa-Free\nMost Caribbean islands allow US citizens visa-free entry (14-90 days):\n- Jamaica: 30 days\n- Bahamas: 90 days\n- Dominican Republic: 30 days (tourist card $10)\n- Turks & Caicos: 30 days\n- USVI/Puerto Rico: Domestic travel`,
    greenCard: `## Green Card Holders — Mostly Visa-Free\nMany Caribbean islands accept US Green Cards for visa-free entry:\n- **Jamaica**: Visa-free with US GC\n- **Dominican Republic**: Tourist card on arrival ($10)\n- **Turks & Caicos**: Visa-free with US GC\n- **Aruba**: Visa-free with valid US visa/GC\n- **Curaçao**: Visa-free with valid US visa/GC\n- **Bahamas**: Visa may be required — check current policy\n- **Barbados**: Visa-free for Indians\n- **St. Lucia**: Visa-free with valid US visa\n- **Antigua**: Visa-free with valid US visa`,
    h1b: `## H-1B Holders — Varies by Island\nWith a valid US visa stamp:\n- **Jamaica**: Visa-free\n- **Aruba**: Visa-free\n- **Dominican Republic**: Tourist card ($10)\n- **Turks & Caicos**: Visa-free\n- **St. Lucia**: Visa-free\n\n### Note: US Visa Must Be Valid\n- Valid stamp required (not just I-797)\n- Check each island's latest requirements before booking`,
    indianPassport: `## Indian Passport (No US Status)\n\nWithout a US visa/GC, most Caribbean islands require a visa or are harder to enter:\n- **Barbados**: Visa-free for 6 months (one of the few!)\n- **Jamaica**: Visa required\n- **Dominican Republic**: Visa required\n- **Trinidad & Tobago**: Visa-free for 30 days\n\nCheck individual embassy websites for current requirements.`,
    consulates: `## Key Caribbean Consulates in USA\n- **Jamaica**: 767 Third Avenue, NY; 1520 S. Dixie Hwy, Miami\n- **Bahamas**: 2220 Massachusetts Ave NW, DC\n- **Dominican Republic**: 1715 22nd Street NW, DC\n- **Trinidad & Tobago**: 1708 Massachusetts Ave NW, DC`,
    applicationProcess: `Most NRIs with US visa/GC don't need to apply for anything — just show up with passport + US status document.\n\nFor those needing visas:\n1. Check specific island's embassy website\n2. Apply with standard tourist visa documents\n3. Processing typically 5-10 days`,
    processingTimes: `- NRIs with US visa/GC: Instant (no visa needed)\n- Tourist visa (where needed): 5-10 business days`,
    costs: `| Destination | Cost for NRIs with US Status |\n|-------------|-----------------------------|\n| Jamaica | Free |\n| Dominican Republic | $10 tourist card |\n| Aruba | Free |\n| Turks & Caicos | Free |\n| Bahamas | Free-$25 (check current) |`,
    tips: `- **All-inclusive vs independent**: Caribbean all-inclusive resorts (Sandals, Hyatt) are great value. But independent travel is cheaper and more authentic.\n- **Hurricane season**: June-November. Best time: December-April.\n- **USVI/Puerto Rico**: If you're in the US, these are domestic travel — no passport needed!\n- **Currency**: Many islands accept USD alongside local currency\n- **Jamaica pro tip**: Montego Bay for resorts, Negril for laid-back beach vibes, Portland for off-the-beaten-path\n- **Aruba**: Year-round good weather (outside the hurricane belt). Great for last-minute trips.`,
    lastUpdated: "2026-05-24",
  },

  {
    destination: "Turkey",
    slug: "turkey-visa",
    category: "middle-east",
    overview: `Turkey — where East meets West. Istanbul, Cappadocia's hot air balloons, and the Turkish Riviera make it a dream destination. NRIs with US visas get easy e-visa access.`,
    usCitizen: `## US Citizens — e-Visa Required\n- Apply at [evisa.gov.tr](https://www.evisa.gov.tr)\n- Cost: $50\n- Validity: 180 days, multiple entry, 90 days per visit\n- Approved instantly online`,
    greenCard: `## Green Card Holders — e-Visa\nIndian passport holders with US GC can use the Turkey e-Visa.\n- Apply at [evisa.gov.tr](https://www.evisa.gov.tr)\n- Select "Indian" nationality\n- Enter US GC details as supporting document\n- Approved instantly\n- Cost: $50`,
    h1b: `## H-1B Holders — e-Visa\nIndian passport holders with valid US visa can get Turkey e-Visa.\n- Same process as GC holders\n- Need valid US visa stamp (not just I-797)\n- Apply at [evisa.gov.tr](https://www.evisa.gov.tr)\n- Instant approval, $50`,
    indianPassport: `## Indian Passport (No US Status)\n\n### e-Visa Available\nIndian passport holders can apply for Turkey e-Visa IF they hold a valid Schengen, US, UK, or Ireland visa/residence permit.\n\n### Without Qualifying Visa\nIf you don't have any of the above, you need a sticker visa from the Turkish consulate.\n\n### Documents for Sticker Visa\n1. Passport\n2. Application form\n3. Photo\n4. Bank statements\n5. Flight and hotel bookings\n6. Travel insurance`,
    consulates: `## Turkish Consulates in USA\n- **Washington DC (Embassy)**: 2525 Massachusetts Ave NW\n- **New York**: 821 United Nations Plaza\n- **Los Angeles**: 6300 Wilshire Blvd\n- **Chicago**: 455 N. Cityfront Plaza Dr\n- **Houston**: 1990 Post Oak Blvd\n- **Boston**: 31 St. James Avenue\n- **Miami**: 100 Biscayne Blvd`,
    applicationProcess: `### e-Visa (for those with US/Schengen/UK visa)\n1. Go to [evisa.gov.tr](https://www.evisa.gov.tr) — official site only!\n2. Select nationality: India\n3. Enter passport and travel details\n4. Select supporting document (US visa, GC, etc.)\n5. Pay $50\n6. Download and print e-Visa — approved instantly\n\n⚠️ BEWARE: Many fake Turkey e-visa websites charge $100+. Only use evisa.gov.tr`,
    processingTimes: `- e-Visa: Instant (literally minutes)\n- Sticker visa (consulate): 5-10 business days`,
    costs: `| Item | Cost |\n|------|------|\n| e-Visa | $50 |\n| Sticker visa | $60-80 |`,
    tips: `- **Cappadocia balloon ride**: Book months in advance. Sunrise flight is magical.\n- **Istanbul**: Get the Istanbulkart for public transport (tram, metro, ferry)\n- **Bazaars**: Grand Bazaar for souvenirs, Spice Bazaar for Turkish delight and spices. Negotiate!\n- **Turkish breakfast**: One of the best breakfast cultures in the world. Try a full spread.\n- **Safety**: Turkey is generally safe for tourists. Standard urban precautions.\n- **Currency**: Turkish Lira (TRY). The lira has been weak — making Turkey very affordable for USD holders.`,
    lastUpdated: "2026-05-24",
  },
];

/* ------------------------------------------------------------------ */
/* Helpers                                                            */
/* ------------------------------------------------------------------ */

export function getGuideBySlug(slug: string): TravelVisaGuide | undefined {
  return TRAVEL_VISA_GUIDES.find((g) => g.slug === slug);
}

export function getGuidesByCategory(category: string): TravelVisaGuide[] {
  if (category === "all") return TRAVEL_VISA_GUIDES;
  return TRAVEL_VISA_GUIDES.filter((g) => g.category === category);
}
