"""
Extended Indian surname list for NPI doctor matching.
~800+ surnames covering North/South/East/West India, 
Sikh, Muslim-Indian, Jain, Christian-Indian names.
"""

INDIAN_SURNAMES_EXTENDED = {
    # --- Existing 234 from indian_relevance.py ---
    "acharya","agarwal","aggarwal","agrawal","ahuja","anand","arora",
    "bajaj","bajpai","bala","balakrishnan","banerjee","bansal","bapat","basu",
    "bedi","bhat","bhatia","bhatt","bhattacharya","bhattacharyya","bose",
    "chakraborty","chand","chandra","chandrasekhar","chatterjee","chaturvedi",
    "chauhan","chawla","chopra","choudhary","choudhury","chowdhury",
    "das","dasgupta","dave","desai","deshmukh","deshpande","devanand","devi",
    "dhawan","dhillon","dixit","doshi","dube","dubey","dutt","dutta",
    "ganesh","ganguly","ghosh","gill","goel","gokhale","gopal","goswami",
    "goyal","guha","gulati","gupta","gupte",
    "iyer","iyengar",
    "jha","jain","jaiswal","johar","jose","joshi","juneja",
    "kadam","kale","kalra","kamath","kamble","kapoor","kar","karnik","kaul",
    "kaur","kaushal","khanna","khatri","kohli","krishna","krishnamurthy",
    "krishnan","kulkarni","kumar","kumari",
    "lal","luthra",
    "madhavan","mahajan","mahalingam","maharaj","majumdar","malhotra","malik",
    "mani","maniar","mathew","mathur","mehta","menon","mishra","misra",
    "mittal","mohapatra","mukherjee","mukhopadhyay","murthy","murty",
    "naidu","nair","nanda","narang","narayan","narayanan","nath","natarajan",
    "nehru","nigam",
    "padmanabhan","pal","palaniappan","pande","pandey","pandit","pandya",
    "parekh","parikh","parmar","patel","pathak","patil","pawar","pillai",
    "poddar","pradhan","prakash","prasad","purohit","puri",
    "raghavan","rai","raj","rajan","rajput","ram","ramachandran","raman",
    "ramakrishnan","rana","rane","ranganathan","rao","rastogi","rathi",
    "rathod","rathore","reddy","roy",
    "sahni","sahu","saini","samant","sanghvi","sanyal","sapra","saraf",
    "sarkar","sarma","sastry","saxena","sen","sengupta","seshadri","seth",
    "shah","shankar","sharma","shastri","sheth","shinde","shivakumar",
    "shukla","siddiqui","singh","sinha","sircar","sitaram","soni",
    "sood","srinivasan","srinivasaraghavan","subramanian","subramaniam",
    "sundaram","suresh","suri","swami","swaminathan",
    "tagore","talwar","tandon","tewari","thakkar","thakur","thapar",
    "tiwari","tiwary","trehan","tripathi","trivedi","tyagi",
    "upadhyay","upadhyaya",
    "vaidya","vaidyanathan","varma","varghese","venkatesh","venugopal",
    "verma","vij","viswanathan","vyas",
    "wadia","wadhwa",
    "yadav",

    # --- Extended: common surnames missed ---
    # North Indian
    "abrol","adani","advani","aneja","arya","awasthi","azad",
    "babbar","bachani","badal","badrinath","bagchi","bahuguna","baid",
    "bakshi","bambawale","bandyopadhyay","banerji","banga","barthwal",
    "basak","batra","baveja","behl","bhagia","bhagwat","bhalla",
    "bhandari","bhandarkar","bhansali","bhardwaj","bhargava","bharti",
    "bhaskaran","bhatnagar","bhavsar","bhowmick","bhowmik","bhutani",
    "bindra","birla","bisht","biswas","bodh","bora","borah","borkar",
    "budhiraja",
    "chakrabarti","chakravarthi","chakravarthy","chakravarti","chakravarty",
    "chanana","chandak","chandrasekar","chandrashekar","chaudhary",
    "chaudhuri","cherian","chibber","chitre","chitnis",
    "dahiya","dalal","dalmia","damle","dandapani","dang","dani","dara",
    "dargan","daruwalla","datta","deodhar","deo","devgan","devnani",
    "dhaka","dhar","dharmadhikari","dhingra","dhir","diwan","dogra",
    "doraiswamy","duggal","dulat",
    "gadgil","gahlot","gaikwad","gala","gambhir","gandhi","ganguli",
    "ganju","garg","gargeya","gaur","gavande","gawande","ghate","ghorpade",
    "gidwani","godse","gogoi","gokul","gondhalekar","gopalakrishnan",
    "gore","govind","govinda","grewal","grover","guleria","gundecha",
    "gurbaxani","gurjar",
    "hajela","halder","hans","handa","hegde","hinduja","hirani",
    "hundal",
    "inamdar","israni",
    "jadhav","jagannathan","jagtap","jagtiani","jaisinghani","jamwal",
    "jaswal","javed","jerath","jetley","jhangiani","jhaveri","jindal",
    "joglekar","jolly","jumani",
    "kadakia","kadambi","kadian","kakar","kakkar","kalia","kalita",
    "kalyanaraman","kalyani","kamboj","kamra","kandhari","kannan",
    "kanodia","kantamneni","kapil","kapur","karande","karkare","karmakar",
    "karpe","kashyap","kataria","katyal","kelkar","keni","keswani",
    "ketkar","khandekar","khandelwal","khare","kher","khera","khosla",
    "kidwai","kini","kirloskar","kochar","kochhar","kolte","koneru",
    "koppikar","korde","korrapati","kothare","kothari","koul",
    "kundra","kundu","kuruvilla",
    "lamba","laxman","limaye","lobo","lodha","lohia","lutchmedial",
    "madhok","madhu","mahashabde","maheshwari","mahindra","maitreya",
    "majmudar","makkar","malviya","manchanda","mangal","mangeshkar",
    "manglik","manjrekar","manohar","marwah","masand","masurkar",
    "mathai","mazumdar","meghani","mehra","mendonca","mirchandani",
    "mirza","mistry","mitra","mohan","mohanty","mohindra","mohite",
    "mokashi","monga","moorthy","morarka","motiwala","moudgil","moza",
    "mudgal","mudaliar","mukhtar","mundle","mundra","munjal","munshi",
    "murali","murti","mushran",
    "nadella","nagpal","nagrath","naik","nambiar","namboodiri",
    "nandakumar","nandi","nangia","narain","nashier","nayak","nayar",
    "nazareth","nene","nimbalkar","nirmal","niyogi","noronha","nuthi",
    "oberoi","ojha",
    "pachauri","padukone","pai","pais","palkar","panicker","panigrahi",
    "panjwani","pant","paradkar","parashar","pardeshi","parrikar",
    "pasricha","patankar","patwardhan","paulose","pawar","pherwani",
    "phadke","phadnis","phansalkar","phatak","phukan","pinto","piramal",
    "pisharody","pitale","pitambaram","poduval","ponnappa","ponkshe",
    "prabhakar","prabhakaran","prabhu","pranesh","prashant",
    "premji",
    "radhakrishnan","raghunath","raghunathan","raheja","rajagopalan",
    "rajagopal","rajaram","rajesh","rajshekhar","ramamurthy","ramamoorthy",
    "ramanathan","ramanujam","ramanujan","ramprasad","ramesh","randhawa",
    "ranganath","rangaswamy","rangan","ranade","raut","ravi","ravichandran",
    "ravindran","rawat","razdan",
    "sabharwal","sachdeva","sachdev","sadanand","sahasrabudhe","sahay",
    "sahgal","saikia","salve","sampath","sampat","samtani","sandhu",
    "sanghavi","sankaran","santhanam","sapru","sarabhai","saran","sarang",
    "sarangi","sardana","sardesai","sarin","sathe","satpathy","savant",
    "sawant","sehgal","sekhon","senthil","seshan","shahani","shaikh",
    "shanbhag","shenoy","shetty","shirodkar","shivpuri","shriram",
    "shrivastav","shrivastava","sidana","sikand","sikka","sindhu",
    "sivakumar","solanki","somani","soman","somayajulu","sonawane",
    "sondhi","sood","soota","sridhar","sridharan","srikant","srikanth",
    "sripada","sriram","srivastava","srivastav","subbarao","subbiah",
    "subrahmanyan","sukhatme","sukumar","sundaresan","sundarrajan","supkar",
    "surana","surya","swaroop",
    "takkar","talreja","tambe","tamhane","taneja","tanejaa","tankha",
    "taparia","tata","tendulkar","thacker","thakare","thampi","thankachan",
    "tharoor","thiruvenkatam","tikoo","tilak","tirth","todkar","topiwala",
    "trikha","tulpule","tungar",
    "udeshi","ullal","unni","uppal",
    "vaish","vaishya","vajpayee","valecha","vanmali","varadarajan",
    "varadhan","varanasi","vasudevan","velankar","vemuri","venkatesan",
    "venkatraman","venkataraman","venkatramani","vijay","vijayan",
    "vikram","vinod","vishwanath","vohra",
    "wagle","wahi","wakankar","wakhlu","walia","wanchoo","warier",
    "warriar",
    "yashwant","yechury","yogananda",
    "zaveri",

    # Sikh surnames (beyond Singh/Kaur/Gill/Dhillon already included)
    "ahluwalia","arshi","aulakh","bains","bassi","bawa","bhachu",
    "bhullar","boparai","cheema","deol","dosanjh","ghotra","ghumman",
    "grewal","hayer","hundal","johal","kahlon","kalsi","kang","khangura",
    "khaira","lakhani","mahal","mand","mangat","matharu","multani",
    "nijjar","pannu","phull","rai","riar","romana","saini","sandhu",
    "sangha","sekhon","sethi","sidhu","sohal","thind","toor","uppal",
    "virdi","virk","wahla",

    # South Indian
    "adiga","aiyer","alagappan","ananthapadmanabhan","annamalai",
    "ashok","ayyar","ayyappan",
    "balachandran","balasubramanian","baliga","bhagavatula",
    "chandrababu","chelladurai","chidambaram","chinnappa",
    "damodaran","doraisamy","eswaran",
    "ganesan","ganapathy","gopalan","govindarajan","gurumurthy",
    "hariharan","jayakumar","jayaraman","jayashankar",
    "kailasam","kalanithi","kalyanasundaram","kamalakannan",
    "kandavel","karuppiah","kathiresan","kesavan","kulandaivelu",
    "lakshmanan","loganathan","madhavan",
    "mahadevan","manivannan","meenakshi","mohandas","murugan",
    "murugesan","muthu","muthukrishnan","muthusamy",
    "nachimuthu","nagarajan","nagappan","nalini","nambi",
    "narasimhan","nehru","padmanaban","palani","palanisamy",
    "pandian","parthasarathy","perumal","ponraj","ponnuswamy",
    "raghavan","rajagopalan","rajendran","ramasamy","ramesh",
    "rangaswamy","ravichandran","ravikumar","rukmini",
    "sadagopan","saravanan","selvaraj","senthilkumar","shanmugam",
    "sivasubramanian","soundararajan","subbu","sudarshan",
    "sundarajan","sundaresan","swaminathan",
    "thiagarajan","thirunavukkarasu","thiruvengadam",
    "udayakumar","vaitheeswaran","vaithianathan","veeramani",
    "veeraraghavan","velayutham","velu","venkatachalam",
    "venkatakrishnan","venkataraman","venugopal","viswanathan",

    # Jain
    "baid","badjatya","bafna","bagmar","bhansali","bohra","bothra",
    "chhajed","chordia","daga","dugar","firodia","gadiya","goenka",
    "jalan","jhunjhunwala","katariya","kedia","lodha","lunawat",
    "mehta","munot","nahar","nahata","nyati","oswal","pagariya",
    "porwal","ranka","sanghvi","sethia","singhi","surana","tapadia",

    # Muslim-Indian (common in Indian medical community)
    "ahmed","akhtar","ali","ansari","azam","aziz",
    "baig","begum","bukhari",
    "farooqi","farooqui",
    "hasan","hashmi","husain","hussain",
    "iqbal","irfan",
    "jafri","jalil",
    "kazmi","khan","khurshid",
    "mirza","momin",
    "naqvi","naseer","nizami",
    "qadri","qureshi","quereshi",
    "rahman","raza","rizvi",
    "saeed","salim","shaikh","siddique","siddiqui","sultan","syed",
    "usmani",
    "waseem","wasi",
    "zaidi","zaman",

    # Christian-Indian (Kerala/Goa/Mangalore)
    "abraham","alexander","chacko","chandy","cherian","d'souza","dsouza",
    "fernandes","george","jacob","john","joseph","kurian","kuruvilla",
    "lobo","mammen","mappillai","mathai","mathew","mendonca","nair",
    "noronha","oommen","paulose","pereira","philip","pinto","pothen",
    "samuel","simon","thomas","varghese","zachariah",

    # Bengali
    "bagchi","bakshi","bandyopadhyay","banik","barua","bhakta",
    "bhattacharjee","bhowmik","biswas","boral","borthakur",
    "chakrabarti","chatterji","deb","debnath","dey","ganguly",
    "ghoshal","goswami","haldar","hazra","karmakar","kundu",
    "lahiri","maitra","mazumder","mitra","mondal","nag","nandi",
    "pakrashi","purkayastha","rakshit","raychaudhuri","roychowdhury",
    "saha","samaddar","sanyal","seal","sengupta","sircar","tarafdar",

    # Gujarati (beyond Patel/Shah/Mehta)
    "amin","barot","bhavsar","chapatwala","dalal","darji","gajjar",
    "gandhi","jani","jobanputra","kakadia","kansara","lakhani",
    "luhar","mistry","modi","naik","pandya","raval","shukla",
    "somaiya","sutaria","thakar","thakkar","trivedi","vaghela","vora",

    # Marathi (beyond Deshmukh/Deshpande/Patil)
    "abhyankar","apte","bhagwat","bhide","chiplunkar","damle",
    "dandekar","datar","deo","gadkari","ghaisas","godbole","jog",
    "joglekar","karandikar","karmarkar","kelkar","khandekar","kirloskar",
    "kolhatkar","kulkarni","lele","limaye","marathe","moghe","mone",
    "nagarkar","natu","ogale","paradkar","paranjape","parulekar",
    "phadke","phatak","ponkshe","ranade","sabnis","sahasrabudhe",
    "sane","sathe","tambe","tamhane","tendulkar","tilak","tulpule",
    "walavalkar",

    # Punjabi (beyond common ones)
    "anand","arora","aurora","babbar","badal","bajwa","banga",
    "behl","bhalla","bhandari","bhardwaj","bhullar","brar","chhabra",
    "chibber","dang","dhingra","duggal","garewal","gulati","handa",
    "jolly","kalra","kamboj","kapila","kathpalia","kaushal","makkar",
    "manchanda","mangla","marwah","mehra","monga","nagpal","nayyar",
    "oberoi","pasricha","sabharwal","sachdeva","sahgal","sarna",
    "sehgal","sodhi","sondhi","talwar","taneja","thapar","trehan",
    "uppal","vohra","wahi","walia",
}

def is_indian_name(first_name: str, last_name: str) -> bool:
    """Check if a person's name is likely Indian-origin."""
    ln = last_name.lower().strip()
    # Direct surname match
    if ln in INDIAN_SURNAMES_EXTENDED:
        return True
    # Check compound surnames (e.g., "BHATTACHARJEE-SMITH")
    for part in ln.split("-"):
        if part.strip() in INDIAN_SURNAMES_EXTENDED:
            return True
    return False

if __name__ == "__main__":
    print(f"Extended Indian surname count: {len(INDIAN_SURNAMES_EXTENDED)}")
