#!/bin/bash
# restore-cron.sh — Restore system cron schedule for The Videshi pipeline
# Writes /etc/cron.d/videshi-pipeline and ensures the cron daemon is running.
# Safe to call repeatedly (idempotent). Called by:
#   - watchdog / health cron
#   - manual recovery
#   - boot catchup
#
# All jobs route through videshi-cron.sh, which handles logging and error tracking.

set -euo pipefail

CRON_FILE="/etc/cron.d/videshi-pipeline"
CRON_SH="/home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh"
LOG="/home/hatch/workspace/cron-logs/watchdog.log"

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*" >> "$LOG"; }

# ── 1. Write the cron schedule ────────────────────────────────────────────────

cat > "$CRON_FILE" <<'CRONTAB'
# /etc/cron.d/videshi-pipeline — auto-generated by restore-cron.sh
# Do not edit manually. Edit restore-cron.sh and re-run it.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOME=/home/hatch

# Load proxy/egress env for all jobs
BASH_ENV=/etc/profile.d/hatch-egress.sh

# ── HOURLY ──
7  * * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh live
12 * * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh v2-ingest
37 * * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh visa-alerts

# ── EVERY 6H ──
22 1,7,13,19  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh dedupe-body-images
27 2,8,14,20  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh ping-google
32 3,9,15,21  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh gmail-scanner

# ── EVERY 12H ──
42 5,17  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh celebrity-buzz
47 6,18  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh pulse-refresh

# ── EVERY 16H (roughly 3x/day) ──
52 4,12,20  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh article-cards

# ── DAILY ──
2  6  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh events-cleanup
4  6  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh topic-cleanup
6  7  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh directory-enrich
8  7  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh credential-check
10 8  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh scrape-meetup
12 8  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh scrape-allevents
14 9  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh scrape-sulekha
16 9  * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh scrape-eventbrite
18 10 * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh media-library
20 10 * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh detect-storylines
22 11 * * *  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh check-dead-images

# ── WEEKLY (Monday) ──
30 7  * * 1  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh streaming-picks

# ── WEEKLY (Friday) ──
0 7  * * 5  root  /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh movie-reviews

# ── BOOT CATCHUP ──
@reboot  root  sleep 30 && /home/hatch/workspace/the-videshi-news/pipeline/videshi-cron.sh catchup

CRONTAB

chmod 644 "$CRON_FILE"

LINES=$(wc -l < "$CRON_FILE")
log "restore-cron.sh: wrote $LINES-line $CRON_FILE"

# ── 2. Ensure cron daemon is running ─────────────────────────────────────────

if systemctl is-active --quiet cron.service 2>/dev/null; then
    log "restore-cron.sh: cron daemon already running (PID $(pgrep -x cron | head -1 || echo '?'))"
else
    log "restore-cron.sh: cron daemon not running, starting..."
    if sudo systemctl start cron.service 2>/dev/null; then
        sleep 1
        if systemctl is-active --quiet cron.service 2>/dev/null; then
            log "restore-cron.sh: cron daemon started (PID $(pgrep -x cron | head -1 || echo '?'))"
        else
            log "restore-cron.sh: CRITICAL — cron daemon failed to start after systemctl"
            exit 1
        fi
    else
        # Fallback: try service command
        if sudo service cron start 2>/dev/null; then
            sleep 1
            log "restore-cron.sh: cron daemon started via 'service cron start'"
        else
            log "restore-cron.sh: CRITICAL — all cron start methods failed"
            exit 1
        fi
    fi
fi

echo "OK: cron schedule restored ($LINES lines), daemon running"
