#!/usr/bin/env python3
"""Immigration writer for The Videshi — 2026-06-13 batch.

Articles:
1. USCIS Signature Rule (July 10 deadline) — practical operational guide for H-1B workers
2. The H-1B Fee Circuit Split — three courts, three circuits, Supreme Court trajectory
"""
import json, os, uuid, re, requests
from datetime import datetime, timezone
from pathlib import Path

# Load env
env_file = Path.home() / ".env.supabase"
for line in env_file.read_text().strip().splitlines():
    if "=" in line and not line.startswith("#"):
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip())

SB_URL = os.environ["SUPABASE_URL"]
SB_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
HEADERS = {
    "apikey": SB_KEY,
    "Authorization": f"Bearer {SB_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation",
}

def sb_post(table, data):
    r = requests.post(f"{SB_URL}/rest/v1/{table}", headers=HEADERS, json=data, timeout=30)
    r.raise_for_status()
    return r.json()

now = datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')

def make_slug(base):
    slug = base.lower()
    slug = re.sub(r'[^a-z0-9\s-]', '', slug)
    slug = re.sub(r'\s+', '-', slug.strip())
    return slug[:70].rstrip('-') + "-" + datetime.now().strftime("%Y%m%d")


# ============================================================
# ARTICLE 1: USCIS Signature Rule — July 10, 2026
# ============================================================

art1_body = """A single missing wet-ink signature. That is all it will take for USCIS to deny your H-1B petition outright, pocket your filing fee, and send you back to the starting line.

On May 11, the agency published an interim final rule that codifies its authority to **deny** — not merely reject — immigration benefit requests that contain invalid signatures. The rule takes effect on July 10, 2026, and it applies to every petition filed on or after that date. For the roughly 344,000 people who filed H-1B petitions this year alone, most of them Indian nationals, the mechanics of this change matter more than the headlines suggest.

## Rejection versus denial — a $2,460 difference

Under existing practice, USCIS has two options when a filing arrives with a defective signature. Rejection means the package is returned unopened, the fee is refunded, and the applicant refiles. Inconvenient, but recoverable.

Denial is something else entirely. USCIS keeps the filing fee — currently $1,710 for the base I-129 petition, plus any applicable fraud prevention and ACWIA fees that can push the total past $2,460. The denial is recorded as a formal adjudication. The petitioner must file a brand-new petition, pay the full fee again, and start over. An appeal via Form I-290B costs an additional $800.

Until now, the regulations only addressed rejection for signature defects. The 2018 USCIS policy memo that authorised denials on signature grounds was guidance, not regulation. The new interim final rule turns that guidance into binding regulatory text with explicit fee-retention authority.

## What USCIS considers invalid

The rule does not change what counts as a valid signature — it changes the penalty for getting it wrong. Here is what the agency considers invalid:

- Copy-pasted or image-affixed signatures lifted from another document
- Typewritten names used as a substitute for a handwritten mark
- Stamped signatures, except in narrow enumerated circumstances
- Signatures by an unauthorised person, such as an attorney signing in place of the petitioner
- Signatures generated by software programs, including DocuSign and similar e-signature platforms

A scanned, faxed, or photocopied version of an originally signed document is acceptable — but only if the original bore a genuine wet-ink signature.

There is no cure provision. If USCIS accepts a petition, begins adjudicating it, and then discovers the signature is defective weeks or months later, it can deny the case without giving the petitioner a chance to correct the error. An officer may issue a Request for Evidence to confirm signatory authority, but not to invite submission of a corrected signature.

## The numbers behind the enforcement push

USCIS says it has seen a documented increase in invalid signatures in recent years, particularly signatures copied from other documents. Total denials on signature grounds rose from 300 in fiscal year 2021 to 2,953 in fiscal year 2025 — a nearly tenfold increase. The Administrative Appeals Office has adjudicated 758 appeals of copied-signature denials. The agency argues that because its intake procedures cannot catch many of these defects at the mailroom stage, officers sometimes reopen and readjudicate cases after significant work has already been performed.

The interim final rule went through without the standard notice-and-comment period. DHS is accepting public comments through July 10 — the same day the rule takes effect.

## What this means for Indian H-1B workers

Indians account for more than 70 per cent of all approved H-1B petitions. The practical exposure is enormous. Consider the typical chain: an employer files an I-129 petition for an H-1B worker, attaching a Labor Condition Application, supporting documentation, and multiple signature pages. The beneficiary signs in one place, the employer representative in another, the attorney in a third. A single defective signature anywhere in that stack — a DocuSign on the I-129, a typed name on the LCA — can trigger denial.

For workers already in the United States on H-1B status, the stakes are existential. A denied extension petition can leave someone out of status. A denied transfer petition can strand a worker between employers. A denied cap petition for FY2027, filed before the June 30 deadline, means the lottery slot is gone.

The rule also catches H-4 EAD applications, I-140 immigrant petitions, and adjustment-of-status filings. Every form filed with USCIS on or after July 10 is subject to the new enforcement framework.

## What to do before July 10

Immigration attorneys are advising clients to audit every signature workflow now. The checklist is short but unforgiving:

- Print every form, sign it by hand with a pen, then scan and submit
- Do not use DocuSign, Adobe Sign, or any e-signature platform for mailed or PDFi-filed petitions
- Confirm that employer representatives and attorneys are not signing on behalf of the petitioner unless specifically authorised
- For attorneys filing via USCIS's PDFi system, electronic signatures are not accepted — only a scanned wet-ink original
- Build signature verification into the filing process as a defined step before submission

The rule does not introduce a new standard. It introduces real consequences for an old one. The cost of ignoring it just became significantly harder to walk back."""

art1 = {
    "id": str(uuid.uuid4()),
    "headline": "One Wrong Signature and USCIS Keeps Your Money — The July 10 Rule Nobody Is Talking About",
    "subheadline": "A new USCIS regulation lets officers deny — not just reject — petitions with defective signatures, forfeiting filing fees with no chance to correct the error.",
    "slug": make_slug("uscis-signature-rule-july-10-deny-petition-filing-fee"),
    "category": "immigration",
    "vertical": "immigration",
    "diaspora_angle": "Indian nationals file over 70% of all H-1B petitions — a single defective signature after July 10 means denial, lost fees, and potentially lost status for workers and their families.",
    "tags": ["uscis", "h1b", "immigration", "signature-rule", "filing-fee"],
    "urgency": "high",
    "sources": json.dumps([
        {"name": "JDSupra / Ogletree Deakins", "url": "https://www.jdsupra.com/legalnews/uscis-rule-raises-stakes-for-signature-9252162/"},
        {"name": "Mintz", "url": "https://www.mintz.com/insights-center/viewpoints/2026-05-12-dhs-issues-interim-final-rule-signature-requirements-uscis"},
        {"name": "Federal Register", "url": "https://www.federalregister.gov/documents/2026/05/11/2026-10412/signatures-on-immigration-benefit-requests"}
    ]),
    "score_total": 82,
    "status": "review",
    "is_editorial": False,
    "published_at": now,
    "image_url": "https://images.pexels.com/photos/48148/document-agreement-documents-sign-48148.jpeg",
    "image_caption": "A hand signs a legal document with a fountain pen — the kind of wet-ink signature USCIS now demands",
    "image_attribution": "Pexels",
    "body": art1_body
}

# ============================================================
# ARTICLE 2: The H-1B Fee Circuit Split
# ============================================================

art2_body = """Three federal judges. Three different courts. Three different answers to the same question: can a president slap a $100,000 fee on an H-1B visa?

On June 8, U.S. District Judge Leo Sorokin in Boston vacated Trump's fee in its entirety, calling it an unconstitutional tax that only Congress can levy. Five months earlier, Judge Beryl Howell in Washington, D.C. upheld the exact same fee, ruling that the president acted within his immigration authority. And in San Francisco, a third lawsuit — filed by religious organisations and labour groups — is still pending before a court in the Ninth Circuit.

The result is a textbook circuit split, the kind of legal contradiction that all but guarantees the Supreme Court will eventually have to weigh in. For the roughly 344,000 people who filed H-1B petitions this year — more than 70 per cent of them Indian nationals — the question of which court's ruling controls is not academic. It determines whether their employer owes $5,000 or $100,000.

## Two judges, opposite conclusions

Judge Howell, an Obama appointee sitting in D.C., ruled in December 2025 that the $100,000 payment was a lawful exercise of presidential authority under the Immigration and Nationality Act. The U.S. Chamber of Commerce had challenged the fee; Howell rejected their arguments. That case is now on appeal before the D.C. Circuit.

Judge Sorokin, also an Obama appointee but sitting in Boston, reached the opposite conclusion. His 42-page ruling found that the fee was a tax — not a penalty, not a restriction, not a regulatory charge. And because only Congress has the constitutional power to levy taxes, Trump's proclamation "did not carry the force of law."

Sorokin's reasoning leaned heavily on the Supreme Court's February 2026 decision striking down Trump's emergency tariffs. In that case, the justices held that sweeping import duties imposed under a national emergency law were, in substance, taxes that the president lacked authority to impose. Sorokin applied the same logic: if tariffs on goods are a tax requiring congressional authorisation, so is a $100,000 charge on visa petitions.

The White House has said it will appeal, and expressed confidence the ruling will be reversed. Spokesperson Taylor Rogers noted that "a federal judge in Washington already upheld a nearly identical order."

That is precisely the problem. When two federal judges look at the same executive action and reach opposite conclusions, the appellate courts must resolve the conflict. And when two different circuit courts disagree, the Supreme Court steps in.

## The San Francisco wild card

A third lawsuit, filed in the Northern District of California by religious groups and labour organisations, adds another variable. If the Ninth Circuit — historically the most sceptical of executive overreach — rules against the fee, that would create a three-circuit split: the First Circuit (Boston) striking it down, the D.C. Circuit potentially upholding it, and the Ninth Circuit weighing in from the West Coast.

Three circuits in conflict would make Supreme Court review nearly certain.

## The eighty-five who already paid

While the courts sort out the legal theory, 85 employers have already paid the $100,000 fee, sending a combined $8.5 million to USCIS. Judge Sorokin's ruling vacated the policy, but neither his decision nor the administration's response has addressed what happens to that money.

If the fee is ultimately ruled unlawful, those employers would presumably be entitled to refunds. But refund mechanisms for vacated agency policies are notoriously slow and uncertain. If the D.C. Circuit upholds the fee on appeal before the First Circuit rules, the legal landscape becomes even murkier — with the fee simultaneously valid in one jurisdiction and void in another.

For employers considering whether to sponsor new H-1B workers, the uncertainty is paralysing. A petition filed today could be subject to the $100,000 fee or exempt from it, depending on which circuit's ruling controls.

## What the tariff precedent means for immigration law

Sorokin's use of the Supreme Court's tariff ruling is the most consequential legal development in this saga. The tariff decision established a broad principle: the executive branch cannot impose financial charges that function as taxes, regardless of what label the administration puts on them.

If that reasoning holds on appeal, it would constrain not just the $100,000 H-1B fee but any future attempt by a president to impose substantial financial charges on visa applications through executive action. Congress, not the White House, would set the price of immigration.

The administration has a counterargument: immigration law gives the president broad authority to "restrict the entry" of foreign nationals deemed detrimental to American interests. A $100,000 charge, they argue, is a restriction, not a tax. But Sorokin rejected that framing outright: "Taxes are not 'restrictions,'" he wrote.

## The timeline ahead

The appeals will take months. The D.C. Circuit will likely hear arguments on the Chamber of Commerce case before the end of 2026. The First Circuit will hear the government's appeal of Sorokin's ruling on a similar timeline. The San Francisco case could move faster or slower depending on judicial scheduling.

The $100,000 fee was originally set to expire on September 21, 2026, one year after Trump's proclamation. But with Congress now pushing the PROTECT Act to codify the fee permanently and the courts still fighting over its legality, the September expiration may be rendered moot by legislation before the judiciary finishes its work.

For Indian H-1B workers and their employers, the practical advice has not changed: budget for uncertainty. The fee may be dead in Boston, alive in Washington, and undecided in San Francisco. Until the Supreme Court speaks — or Congress acts — nobody knows what the H-1B programme costs."""

art2 = {
    "id": str(uuid.uuid4()),
    "headline": "Three Courts, Three Answers, One Fee — The H-1B Circuit Split Heading to the Supreme Court",
    "subheadline": "A Boston judge struck down the $100,000 fee. A Washington judge upheld it. A San Francisco case is pending. The contradiction all but guarantees the Supreme Court will decide.",
    "slug": make_slug("h1b-fee-circuit-split-supreme-court-three-courts"),
    "category": "immigration",
    "vertical": "immigration",
    "diaspora_angle": "Indian nationals account for over 70% of H-1B petitions — the circuit split means employers in different states face contradictory rules on whether they owe $5,000 or $100,000.",
    "tags": ["h1b", "uscis", "supreme-court", "circuit-split", "immigration-fee"],
    "urgency": "high",
    "sources": json.dumps([
        {"name": "Reuters", "url": "https://www.reuters.com/world/trumps-100000-h-1b-visa-fee-is-unlawful-us-judge-rules-2026-06-08/"},
        {"name": "Audacy / AP", "url": "https://www.audacy.com/national-news/federal-judge-strikes-down-trumps-dollar100k-h-1b-visa-fee"},
        {"name": "Wall Street Journal", "url": "https://www.wsj.com/politics/policy/judge-strikes-down-trump-administrations-100-000-h-1b-visa-fee-d2b8e1a5"},
        {"name": "Fox News", "url": "https://www.foxnews.com/politics/federal-judge-strikes-down-trumps-100k-h-1b-visa-fee-ruling-unconstitutional-tax"}
    ]),
    "score_total": 85,
    "status": "review",
    "is_editorial": False,
    "published_at": now,
    "image_url": "https://images.pexels.com/photos/11363782/pexels-photo-11363782.jpeg",
    "image_caption": "A judge's gavel rests on US dollar bills beside an American flag — the fee's legality now splits three federal circuits",
    "image_attribution": "Pexels",
    "body": art2_body
}

# ============================================================
# Insert articles
# ============================================================
articles = [art1, art2]

for art in articles:
    try:
        sb_post("p2_articles", art)
        print(f"✅ {art['slug']}")
    except Exception as e:
        print(f"❌ {art['slug']}: {e}")
