#!/usr/bin/env python3
"""Videshi Technology Writer — 2026-06-27 11:00 PT"""
import json, os, uuid, re, requests
from datetime import datetime, timezone
from pathlib import Path

# Load env
env_file = Path.home() / ".env.supabase"
for line in env_file.read_text().strip().splitlines():
    if "=" in line and not line.startswith("#"):
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip())

SB_URL = os.environ["SUPABASE_URL"]
SB_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
HEADERS = {
    "apikey": SB_KEY,
    "Authorization": f"Bearer {SB_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation",
}

def sb_post(table, data):
    r = requests.post(f"{SB_URL}/rest/v1/{table}", headers=HEADERS, json=data, timeout=30)
    r.raise_for_status()
    return r.json()

now = datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z')

def make_slug(base):
    slug = base.lower()
    slug = re.sub(r'[^a-z0-9\s-]', '', slug)
    slug = re.sub(r'\s+', '-', slug.strip())
    return slug[:70].rstrip('-') + "-" + datetime.now().strftime("%Y%m%d")

# ─────────────────────────────────────────────────────────────
# ARTICLE 1: RBI AI Kill Switch for Banks
# Beat: D — AI Regulation / Indian Tech Ecosystem
# ─────────────────────────────────────────────────────────────

art1_body = """The Reserve Bank of India has proposed what may be the world's most detailed regulatory framework for artificial intelligence in banking — and its centrepiece is a mechanism that sounds borrowed from science fiction: a mandatory kill switch for every AI model deployed by a financial institution.

The draft *Guidance on Regulatory Principles for Model Risk Management, 2026*, released on June 24, applies to commercial banks, small finance banks, NBFCs, payment banks, cooperative banks, regional rural banks, asset reconstruction companies, and credit information companies. In other words, virtually every entity that touches Indian retail finance.

## What the Rules Demand

The framework requires regulated entities to build mechanisms that can override, suspend, or completely deactivate any AI model — instantly, on command. Banks must establish what the RBI calls "human-in-the-loop arrangements," including explicit kill-switch capabilities, override features, and periodic human review of AI-generated decisions.

For customer-facing AI systems — the chatbots, virtual assistants, and recommendation engines that millions of account holders interact with daily — the rules go further. Banks must disclose when customers are interacting with an AI system, communicate its limitations, and provide an option to switch to a human representative at any time. Generative AI systems that interface with customers must also be protected against prompt injection attacks and adversarial inputs.

Third-party AI models, including those from global technology vendors, receive no exemptions. Banks remain fully accountable for outcomes generated by external AI systems. Every third-party model must undergo independent validation before deployment, and institutions must secure audit rights for both themselves and the RBI.

## Why NRIs Should Care

The guidelines matter well beyond Mint Street. Millions of non-resident Indians hold NRE and NRO accounts, invest through Indian brokerage platforms, send remittances via UPI, and interact with bank chatbots that increasingly make credit, pricing, and risk decisions. If an AI model at an Indian bank goes rogue — mispricing a fixed deposit, erroneously flagging a cross-border transaction as fraudulent, or drifting on credit scoring in a way that disadvantages NRI applicants — the RBI now wants a red button that shuts it down before the damage compounds.

The framework also mandates board-level oversight. Every institution must establish a board-approved Model Risk Management Framework covering governance, classification, validation, deployment, monitoring, and decommissioning. Decommissioned models must remain documented for at least ten years.

## A Global Benchmark

The RBI's approach is arguably more prescriptive than what Western regulators have attempted. The EU AI Act takes a risk-based approach but does not mandate kill switches or customer-facing transparency at this level of specificity. The Federal Reserve has issued general guidance on model risk but nothing comparable in scope for AI-specific systems. India's framework sits closer to what the Bank of England has hinted at — but the RBI appears to have got there first.

Industry reaction has been cautiously positive. "The guidance removes the bigger blocker: uncertainty," said Ajay Sirikonda, Partner and Leader for Financial Services Risk Management at EY India. "Banks have sat on AI not just because it was costly, but because no one had said what was allowed."

The draft is open for public consultation until July 24. Once finalised, it will replace the RBI's existing 2002 guidance on credit risk models — a framework drafted in an era when the most advanced model in Indian banking was a spreadsheet."""

art1 = {
    "id": str(uuid.uuid4()),
    "headline": "India's Central Bank Just Ordered a Kill Switch on Every AI System in Banking",
    "subheadline": "The RBI's draft framework demands board-level oversight, mandatory human alternatives for customers, and the ability to shut down any AI model on command — the most prescriptive rules of their kind anywhere.",
    "slug": make_slug("rbi-ai-kill-switch-banking-regulation-nri"),
    "category": "technology",
    "vertical": "fintech",
    "diaspora_angle": "Millions of NRIs hold Indian bank accounts, invest through AI-powered platforms, and send remittances via UPI — all systems now subject to the RBI's strictest-ever AI governance rules.",
    "tags": ["ai-regulation", "rbi", "indian-banking", "fintech", "nri-banking"],
    "urgency": "medium",
    "sources": json.dumps([
        {"name": "Reuters", "url": "https://www.reuters.com/world/india/rbi-proposes-guidelines-banks-manage-ai-risks-2026-06-24/"},
        {"name": "Exchange4media", "url": "https://www.exchange4media.com/digital-news/no-black-box-ai-rbi-proposes-strict-governance-framework-for-banks-ai-systems-155794.html"},
        {"name": "Outlook Business", "url": "https://www.outlookbusiness.com/economy-and-policy/why-rbi-wants-banks-to-put-tighter-checks-on-ai-use"},
        {"name": "The420.in", "url": "https://www.the420.in/new-rbi-guidelines-mandate-immediate-kill-switches-to-control-banking-ai/"}
    ]),
    "score_total": 78,
    "status": "review",
    "is_editorial": False,
    "published_at": now,
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Tower_and_building_of_Reserve_Bank_of_India%2C_Mumbai_02.jpg/1280px-Tower_and_building_of_Reserve_Bank_of_India%2C_Mumbai_02.jpg",
    "image_caption": "The Reserve Bank of India headquarters in Mumbai",
    "image_attribution": "Wikimedia Commons",
    "body": art1_body.strip()
}

# ─────────────────────────────────────────────────────────────
# ARTICLE 2: Skyroot Vikram-1 Orbital Countdown
# Beat: C — Indian Tech Ecosystem / Space Tech
# ─────────────────────────────────────────────────────────────

art2_body = """At a spaceport on the southeastern coast of Andhra Pradesh, a 23-metre rocket sits in its final stages of integration. Vikram-1, named after Vikram Sarabhai — the father of India's space programme — is not an ISRO creation. It was designed, built, and tested by a Hyderabad startup staffed largely by engineers who left ISRO to do what the government agency never let them: move fast.

Skyroot Aerospace, India's first space tech unicorn, is now weeks from attempting the country's first privately developed orbital launch. If it succeeds, India joins an exclusive club of nations where private companies can reach orbit. If it fails, a billion-dollar valuation and half a decade of promises reset overnight.

## The Money Behind the Rocket

In May, Skyroot closed a $60 million round that valued the company at $1.1 billion on a pre-money basis — a figure that more than doubled its previous valuation. The lead investors read like a who's who of global capital: GIC (Singapore's sovereign wealth fund), Sherpalo Ventures (founded by Ram Shriram, an Alphabet board member and early Google backer), and BlackRock.

Shriram's involvement carries symbolic weight. An Indian-American who helped build the most valuable technology company on Earth, he is now backing a bet that India can build rockets to match. He has joined Skyroot's board.

The round brought total capital raised to $160 million. The company said proceeds will scale Vikram-1 launch operations, expand manufacturing at its 200,000-square-foot Max-Q campus in Hyderabad, and accelerate development of Vikram-2 — a more powerful vehicle with a cryogenic upper stage capable of carrying one tonne to low Earth orbit.

## The Technical Stakes

Vikram-1 is designed to deliver up to 350 kilograms to low Earth orbit — comparable to Rocket Lab's Electron and Firefly Aerospace's Alpha. Its four-stage architecture includes solid-fuelled first through third stages and a hypergolic liquid upper stage (four Raman-I engines) for precise orbital injection. Skyroot claims the rocket can be assembled and launched within 24 hours, a turnaround time that would make it competitive for the dedicated small-satellite launch market.

The company completed its pre-flight integrated test campaign in April, flagging off the rocket from Hyderabad to the Satish Dhawan Space Centre at Sriharikota with a ceremony led by Telangana's Chief Minister. But orbital rocketry is merciless. As of late June, neither Skyroot nor its Chennai-based rival Agnikul Cosmos has completed a successful commercial orbital mission. Skyroot's 2022 sub-orbital launch of Vikram-S proved the technology; Vikram-1 must prove the business.

## What This Means for the Diaspora

India's government has set an ambitious target: expand the country's space industry from $8.4 billion today to $44 billion by 2033, roughly 8 per cent of the global space economy. Private launch capability is essential to that plan, especially as ISRO has suffered consecutive orbital launch failures.

For NRI investors and professionals, the story has direct relevance. Skyroot's co-founders Pawan Kumar Chandana and Naga Bharath Daka are IIT Kharagpur graduates who left ISRO to build the company. The investor roster — Temasek, GIC, BlackRock, the Greenko Group founders — offers public-market exposure to India's space ambitions once the company inevitably lists. And the broader ecosystem it anchors — 200-plus registered space startups, an IN-SPACe regulatory body that has liberalised access to ISRO infrastructure, and partnerships like Skyroot's MoU with Axiom Space — creates a new corridor for diaspora capital and talent.

The rocket is on the pad. Now it has to fly."""

art2 = {
    "id": str(uuid.uuid4()),
    "headline": "India's First Private Orbital Rocket Is on the Launchpad. A Billion-Dollar Bet Rides on It.",
    "subheadline": "Skyroot Aerospace, now valued at $1.1 billion with backing from Alphabet's Ram Shriram, GIC, and BlackRock, is weeks from attempting what no Indian private company has done.",
    "slug": make_slug("skyroot-vikram-1-orbital-launch-india-space-unicorn"),
    "category": "technology",
    "vertical": "space-tech",
    "diaspora_angle": "Founded by IIT-trained ex-ISRO engineers and backed by Silicon Valley legend Ram Shriram, Skyroot's launch anchors a $44 billion space sector that NRI investors and professionals increasingly have stakes in.",
    "tags": ["space-tech", "skyroot", "isro", "startup", "indian-tech"],
    "urgency": "medium",
    "sources": json.dumps([
        {"name": "TechCrunch", "url": "https://techcrunch.com/2026/05/07/indias-first-space-tech-unicorn-emerges-as-skyroot-gears-up-for-orbital-launch/"},
        {"name": "Reuters", "url": "https://www.reuters.com/technology/space/indias-skyroot-becomes-first-1-bln-space-tech-startup-with-gic-sherpalo-blackrock-2026-05-07/"},
        {"name": "Analytics Insight", "url": "https://www.analyticsinsight.net/space-tech/can-india-become-the-next-spacex-success-story"},
        {"name": "AirPro News", "url": "https://airpronews.com/space-satellites/skyroot-aerospace-dispatches-vikram-1-orbital-rocket-to-spaceport/"}
    ]),
    "score_total": 80,
    "status": "review",
    "is_editorial": False,
    "published_at": now,
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Vikram-S_rocket%27s_Mission_Prarambh.png/1280px-Vikram-S_rocket%27s_Mission_Prarambh.png",
    "image_caption": "Skyroot Aerospace's Vikram-S rocket during its 2022 sub-orbital launch from Sriharikota",
    "image_attribution": "Wikimedia Commons",
    "body": art2_body.strip()
}

# ─────────────────────────────────────────────────────────────
# ARTICLE 3: Nikesh Arora / Palo Alto Networks AI Bet
# Beat: A — Indian-Origin Tech Leaders
# ─────────────────────────────────────────────────────────────

art3_body = """Nikesh Arora has a message for anyone who thinks artificial intelligence will kill the cybersecurity industry: you are confused, and his stock price agrees.

Palo Alto Networks, the $240 billion cybersecurity giant led by the Indian-born CEO, hit a new 52-week high this week at $306, capping a remarkable recovery from the panic that gripped software stocks earlier this year. While the rest of the software world worried that AI would make their products obsolete, Arora quietly doubled his company's share price — and spent $10 million of his own money buying the dip along the way.

## The Vulnerability Machine

The latest catalyst came this week, when Arora revealed on the *Twenty Minute VC* podcast that Palo Alto had used Mythos — Anthropic's frontier AI model that was deemed too powerful for unrestricted release — to discover five years' worth of software vulnerabilities in just six weeks. The demonstration was not an academic exercise. It was proof of concept for Arora's central thesis: that AI dramatically expands the attack surface, and the companies best positioned to exploit AI for defence will see demand surge, not collapse.

"I'm still confused why the market is treating AI as a threat" to cybersecurity, Arora told analysts during the company's fiscal third-quarter earnings call in early June. The numbers backed him up. Revenue rose to $3 billion for the quarter, up from $2.6 billion a year earlier, and the company raised its full-year outlook. More than 110 enterprise customers completed what Palo Alto calls "platformizations" during the quarter — consolidating fragmented cybersecurity tools onto Palo Alto's unified platform.

## The Platform Play

Arora's strategy rests on a bet that enterprises drowning in point-solution cybersecurity products will consolidate. A typical large company might run forty or fifty separate security tools from different vendors — firewalls from one, endpoint detection from another, cloud security from a third. Palo Alto's pitch: collapse them all into one platform, and use AI to correlate threats across the entire stack.

The market was initially sceptical. When Arora announced the platformization strategy in February 2024, the stock dropped. Two years later, the results are hard to argue with. Customers who platformize spend more, renew at higher rates, and give Palo Alto visibility into threats that fragmented competitors simply cannot match.

"To the extent we are creating proprietary data in security, that is not going to be replaced by an LLM," Arora said. The argument is compelling: Palo Alto sees real-world threat data from thousands of enterprises, and that proprietary corpus — not publicly available training data — is what makes its AI models useful. An AI without threat intelligence is just a very fast guesser.

## The Diaspora Angle

Arora's career arc is a case study in the Indian-origin tech leader's playbook — one that increasingly runs through cybersecurity. Born in Uttar Pradesh, educated at IIT Varanasi and Northeastern University, he spent 10 years at Google as Chief Business Officer (reporting directly to Larry Page) before a high-profile stint as president of SoftBank. He took the Palo Alto Networks CEO role in 2018 and has since built it into the world's most valuable pure-play cybersecurity company.

For Indian tech professionals in the US — particularly those at enterprises now under pressure to upgrade their security posture against AI-powered threats — Arora's ascent matters. Cybersecurity is one of the fastest-growing segments in enterprise technology, projected to reach $300 billion globally by 2028. It is also one of the few sectors where AI is an unambiguous tailwind, not a headwind that threatens jobs.

Around 1,000 companies reached out to Palo Alto over the past two months, Arora disclosed, "to talk about their cyber posture, cyber infrastructure, and how we can help them get through this period of living the future with frontier AI models being cyber-capable." The development of models like Anthropic's Claude Mythos — powerful enough that Anthropic offered early access to cyber defenders before general release — has made the conversation urgent.

For once, the cybersecurity industry's perennial message of fear is also its growth story. Nikesh Arora just happens to be the one selling both."""

art3 = {
    "id": str(uuid.uuid4()),
    "headline": "Nikesh Arora's Palo Alto Networks Hit an All-Time High. His Bet: AI Makes Hackers Worse, Not Cybersecurity Obsolete.",
    "subheadline": "The Indian-born CEO used Anthropic's frontier model to find five years of vulnerabilities in six weeks. His $240 billion company has doubled while the market panicked over software's future.",
    "slug": make_slug("nikesh-arora-palo-alto-networks-ai-cybersecurity-record"),
    "category": "technology",
    "vertical": "cybersecurity",
    "diaspora_angle": "Indian-born Nikesh Arora, an IIT alum and former Google executive, leads the world's most valuable cybersecurity company at a moment when AI-driven threats are creating massive demand for security talent and platforms.",
    "tags": ["nikesh-arora", "palo-alto-networks", "cybersecurity", "ai", "indian-tech-leaders"],
    "urgency": "medium",
    "sources": json.dumps([
        {"name": "TradersUnion", "url": "https://tradersunion.com/interesting-articles/view/palo-alto-networks-stock-jumps-as-palo-alto-networks-touts-ai-driven-vulnerability-discoveries/"},
        {"name": "CRN", "url": "https://www.crn.com/news/security/2025/palo-alto-networks-ceo-ai-won-t-replace-security-tools-any-time-soon"},
        {"name": "Morningstar", "url": "https://www.morningstar.com/news/marketwatch/20260328257/palo-alto-networks-ceo-sends-a-message-through-his-10-million-stock-purchase"},
        {"name": "Cybersecurity Dive", "url": "https://www.cybersecuritydive.com/news/palo-alto-networks-arora-ai-demand-driver-threat/740300/"}
    ]),
    "score_total": 82,
    "status": "review",
    "is_editorial": False,
    "published_at": now,
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/e/ea/Nikesh_Arora_TechCrunch_Disrupt_2015.jpg",
    "image_caption": "Nikesh Arora, CEO of Palo Alto Networks, at TechCrunch Disrupt",
    "image_attribution": "Wikimedia Commons",
    "body": art3_body.strip()
}

# ─────────────────────────────────────────────────────────────
# INSERT
# ─────────────────────────────────────────────────────────────

articles = [art1, art2, art3]

for art in articles:
    try:
        sb_post("p2_articles", art)
        print(f"✅ {art['slug']}")
    except Exception as e:
        print(f"❌ {art['slug']}: {e}")
