#!/usr/bin/env python3
"""Trim 3 article bodies to 500-800 words and PATCH them."""
import json, os, re, subprocess

SUPABASE_URL = os.environ["SUPABASE_URL"]
KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]

def curl(method, path, data=None, params=""):
    cmd = ["curl", "-sS", "-X", method,
           f"{SUPABASE_URL}/rest/v1/{path}{params}",
           "-H", f"apikey: {KEY}",
           "-H", f"Authorization: Bearer {KEY}",
           "-H", "Content-Type: application/json",
           "-H", "Prefer: return=representation"]
    if data is not None:
        cmd += ["-d", json.dumps(data)]
    out = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return out.stdout

def wc(html):
    text = re.sub(r"<[^>]+>", " ", html)
    return len([w for w in text.split() if w.strip()])

patches = {}

# ---------- Article 1: Swara ----------
patches["d774eb31-2f18-4f2c-a8e8-b0f8a7b74ca6"] = """<div class="key-takeaways"><ul><li>Swara Bhasker says Salman Khan personally mentored her during 2015's <em>Prem Ratan Dhan Payo</em>, coaching her on camera craft, styling and "the psychology of stardom."</li><li>The actor has repeatedly argued that streaming has "democratised creativity and stardom," opening space for new stories outside the box-office system.</li><li>Bhasker attributes Bollywood's box-office slump to an economic slowdown, COVID-19 and the rise of OTT — not only to boycott campaigns.</li><li>Her outspoken assessments span the Khans' three-decade dominance and the industry's shifting audience tastes.</li></ul></div>
<p>Swara Bhasker has never treated celebrity as a gag order. In a run of candid interviews — from trade conversations to a recent sit-down that has reignited debate about where Hindi cinema stands — the actor has laid out an unusually blunt account of Bollywood's evolution: the three-decade reign of the Khans, the arrival of streaming as a creative equaliser and an industry being forced to rethink its storytelling.</p>
<h2>The Khans and the star machine</h2>
<p>Bhasker entered Hindi cinema in 2009 and broke through with <em>Tanu Weds Manu</em> (2011), <em>Raanjhanaa</em> (2013) and <em>Nil Battey Sannata</em> (2016), straddling big commercial titles such as <em>Prem Ratan Dhan Payo</em> (2015) and <em>Veere Di Wedding</em> (2018), and independent cinema.</p>
<p>On the sets of the 2015 Sooraj Barjatya blockbuster, where she played Salman Khan's sister, the superstar took an unexpected interest in her trajectory. "What surprised me most was how invested Salman was in transforming me," Bhasker said in a recent interview. "He wasn't just focused on his own performance — he was actively thinking about my career trajectory and how to position me as a leading lady." Khan coached her on camera angles and lighting specific to heroines, carrying traditional outfits and screen presence — what she called "the psychology of stardom."</p>
<blockquote class="pull-quote"><p>"Working with Salman in a Sooraj Barjatya film was like a masterclass in mainstream cinema."</p><cite>— Swara Bhasker</cite></blockquote>
<p>Her reading of the star system has long circled around Shah Rukh Khan, Salman Khan and Aamir Khan. "An actor can become a star, but to retain that position like SRK, Salman or Aamir for 25 years is difficult," she said at a 2017 industry event. Nine years later, trade analysts say Hindi cinema still has not built a successor generation to replace them.</p>
<h2>OTT as the great leveller</h2>
<p>Bhasker's most sustained argument concerns streaming. In a 2020 interview with Bollywood Hungama's Subhash K. Jha, she said: "OTT platforms have not only changed content by opening up a space for new stories, new characters and new ideas to be accepted, they have also democratised content. They've democratised creativity and by giving a platform to talented new and old actors OTT has democratised stardom."</p>
<p>She cautioned that the old order had not finished adapting: "It is yet to be seen how the traditional box office determined ecosystem of theatrical cinema will readjust to this change." Six years on, that readjustment is still underway, with 2026 box-office data showing theatrical revenues increasingly concentrated in a handful of tentpoles.</p>
<h2>The boycott debate</h2>
<p>When India Today asked her about the 'Boycott Bollywood' campaigns, Bhasker called the attempts to bring the industry down "petty and disgusting," pointing out that it provides livelihoods to thousands. Quoting director Anurag Kashyap, she said the country's economic slump explained part of the downturn — along with COVID-19 and OTT drawing audiences away from theatres. "After the unfortunate and tragic suicide of Sushant, Bollywood has been painted as a really dark place, that is only about drugs and alcohol and sex," she said.</p>
<h2>A reckoning with her own films</h2>
<p>Bhasker has also turned her candour on her own filmography. In a 2025 conversation with Hauterrfly, she revisited the controversy over <em>Raanjhanaa</em> (2013), criticised for glorifying stalking, admitting she had not recognised the problem while making it. "India is full of 'naskatuye aashiq'," she said, arguing that Hindi cinema's biggest hits keep returning to the suffering male hero: "Mardon ki bechargi se zyada profitable art mein kuch nahi hai" — nothing is more profitable in art than stories about victimised men, citing <em>Raanjhanaa</em>, <em>Devdas</em> and <em>Saiyaara</em>.</p>
<blockquote class="pull-quote"><p>"OTT platforms have not only changed content by opening up a space for new stories, new characters and new ideas to be accepted, they have also democratised content."</p><cite>— Swara Bhasker, on streaming</cite></blockquote>
<h2>Impact and analysis</h2>
<p>Bhasker's position — commercial insider and outspoken outsider — makes her a useful barometer. Her remarks connect the threads of the moment: a concentrated star system struggling to produce new headliners, the streaming correction that rewrote distribution economics and audiences migrating toward southern-language cinema. She has also been open about the personal cost, saying producers have told her she carries "nuisance value" and that her activism cost her work.</p>
<h2>Diaspora angle</h2>
<p>For diaspora audiences, whose Hindi-film viewing now runs overwhelmingly through streaming, Bhasker's argument that OTT has "democratised stardom" describes how NRIs already experience Bollywood — with smaller films and regional titles a click away from the tentpoles.</p>
<h2>What's next</h2>
<p>Bhasker is currently seen on the reality show <em>Pati Patni Aur Panga</em>. Whether her political candour continues to limit her casting — a tradeoff she has described as "conscious" — will test how much room the industry genuinely has for dissent.</p>
"""

# ---------- Article 2: Bollywood dominance ----------
patches["db228cef-691e-48d9-8d63-cc660d4d164f"] = """<div class="key-takeaways"><ul><li>India's domestic box office reached ₹8,147 crore through July 2026, up 13% year on year — but Hindi cinema's share has slipped below 40% for the first time this year, to 38%.</li><li>Hollywood's share hit a record 17%, beating its 2019 peak of 15%; <em>Spider-Man: Brand New Day</em> crossed ₹500 crore to become the highest-grossing international film ever in India.</li><li>Telugu (18%), Tamil (13%) and Malayalam (7%) cinema now claim a combined 38% of domestic revenue — matching Hindi's entire share.</li><li>July's four biggest releases captured 81% of the month's collections, with <em>Spider-Man</em> alone taking 40%.</li></ul></div>
<p>On paper, Indian cinema is enjoying one of its strongest commercial runs since the pandemic. Through the first seven months of 2026, cumulative gross domestic collections reached ₹8,147 crore — up 13% compared with the same period in 2025, according to Ormax Media data reported by CNBC TV18. July alone added ₹1,582 crore, the second-highest-grossing month of the year so far.</p>
<p>But beneath the record topline, the money is moving away from Mumbai. For the first time in 2026, Hindi cinema's share of the domestic box office has slipped below 40%, settling at 38% through July — down sharply from the 44% it commanded at the end of June. The ground it lost has been captured by Hollywood spectacles and consistent regional blockbusters.</p>
<h2>Hollywood's record run</h2>
<p>The primary disruptor in 2026 has been international cinema, which expanded its domestic footprint to a record-high 17% share of total Indian box-office revenue through July. Hollywood's previous annual best stood at 15% in 2019.</p>
<p>Driving the surge was <em>Spider-Man: Brand New Day</em>, which grossed over ₹500 crore — surpassing <em>Avatar: The Way of Water</em> to become the highest-grossing international film of all time in India, and the second-highest-grossing film of 2026 overall. It trails only <em>Dhurandhar: The Revenge</em>, which crossed the ₹1,000 crore mark domestically to become the highest-grossing Hindi film of all time. Coupled with Christopher Nolan's <em>The Odyssey</em> (₹220 crore), international films generated over ₹1,424 crore between January and July — putting Hollywood on track to eclipse its pre-pandemic 2019 revenue record of ₹1,595 crore well before the year-end release of <em>Avengers: Doomsday</em>.</p>
<h2>The regional surge</h2>
<p>Telugu cinema currently commands an 18% share of the domestic box office, Tamil cinema holds 13%, and Malayalam and other regional languages account for 7% each — a combined 38%, equal to Hindi's entire share.</p>
<p>The shift shows up in the year's top titles. Across the top 10 domestic releases of 2026 through July, Hindi cinema accounts for four — <em>Dhurandhar: The Revenge</em>, <em>Border 2</em>, <em>Bhooth Bangla</em> and <em>Dhamaal 4</em> — while Telugu (<em>Peddi</em>, <em>Mana Shankara Vara Prasad Garu</em>), Tamil (<em>Jana Nayagan</em>, <em>Karuppu</em>) and Hollywood (<em>Spider-Man</em>, <em>The Odyssey</em>) claim two spots each. Ormax's April data had Hindi at a 50% share; by July that lead had evaporated.</p>
<h2>A two-tentpole economy</h2>
<p>The strong headline hides a fragile structure. Ashish Misra, head of commercialisation at Cinepolis India, notes that Q1 2026's ₹3,440 crore — 17% higher than Q1 2025 — was shaped by "two large tentpoles at the bookends," while February, at under ₹500 crore, was the softest month since February 2023.</p>
<blockquote class="pull-quote"><p>"The headline is strong, the curve underneath it is still uneven. That distinction matters because it tells us where the work still is."</p><cite>— Ashish Misra, Head of Commercialisation, Cinepolis India</cite></blockquote>
<p>Misra identifies the missing middle as the real task: building "a steady flow of films in the ₹50 to ₹200 crore band that keep occupancy healthy week on week" between the tentpoles. July illustrates the concentration: the top four releases — <em>Spider-Man: Brand New Day</em>, the Tamil blockbuster <em>Jana Nayagan</em> (₹230 crore), <em>The Odyssey</em> (₹220 crore) and the Hindi comedy <em>Dhamaal 4</em> (₹197 crore) — accounted for 81% of the month's receipts, with <em>Spider-Man</em> generating 40% on its own.</p>
<h2>Impact and analysis</h2>
<p>The squeeze has two engines. Hollywood franchises open day-and-date with massive dubbed footprints and premium-format pricing, pulling the top end of the audience. Regional cinema is eating the middle: it recovered faster from the pandemic, takes bigger creative risks and now releases pan-India with Hindi dubs as a matter of course. For Bollywood, the danger is not a bad year — 2026 is, in aggregate, a record one — but a shrinking claim on it. When a single Hollywood title can outgross every Hindi release of the month except the year's biggest, the centre of gravity has moved.</p>
<h2>Diaspora angle</h2>
<p>Overseas, diaspora audiences mirror the trend: <em>Spider-Man: Brand New Day</em> also reclaimed the No. 1 global box-office spot, while Telugu and Tamil blockbusters continue to fill North American multiplexes — the same screens where Hindi tentpoles once had the weekend to themselves.</p>
<h2>What's next</h2>
<p>The second half of 2026 is packed: <em>Ramayana: Part 1</em>, <em>King</em>, <em>Toxic</em>, <em>Fauzi</em>, <em>Jailer 2</em> and <em>Avengers: Doomsday</em>. Ormax's first-half report put January-June at ₹6,398 crore — the strongest post-pandemic first half — and said 100 crore annual footfalls remain achievable. Whether Hindi cinema reclaims share will depend on the festival slate, not the record books.</p>
"""

# ---------- Article 3: Female cops ----------
patches["4a64973b-0368-44f3-9429-6b40c35004da"] = """<div class="key-takeaways"><ul><li>Rediff critic Sukanya Verma spotlights Hindi cinema's new wave of women in uniform, from Kareena Kapoor Khan's "cop who wears lipstick" in <em>Daayra</em> to Rani Mukerji's Shivani Shivaji Roy in the <em>Mardaani</em> films.</li><li><em>Mardaani 3</em> closed its 2026 theatrical run at about ₹77 crore — the franchise's best — completing the first hattrick of hits for a female-cop series in 113 years of Hindi cinema.</li><li>Streaming drove the shift: <em>Delhi Crime</em>, <em>Dahaad</em>, <em>Aranyak</em>, <em>Kohrra</em> and <em>Brown</em> gave women investigators sustained screen time after Netflix's 2016 India entry rewrote the economics of risk.</li><li>Actresses say the draw is complexity, not the uniform: flawed protagonists whose vulnerability and competence coexist.</li></ul></div>
<p>In early 2026, Rani Mukerji's <em>Mardaani 3</em> closed its theatrical run earning about ₹77 crore — the highest-grossing film in the 12-year-old franchise's history. According to Bollywood Hungama, it made the <em>Mardaani</em> series the only female-cop franchise to succeed in 113 years of Hindi cinema, landing an unprecedented hattrick of hits. For Rediff film critic Sukanya Verma, the milestone is part of a wider turn: from Kareena Kapoor Khan's "cop who wears lipstick" in <em>Daayra</em> to Mukerji's relentless Shivani Shivaji Roy, Bollywood's portrayals of female police officers have grown more powerful — and more nuanced.</p>
<h2>A long history of one-offs</h2>
<p>Women in uniform have appeared in Indian cinema since at least the 1980s. They just never stayed long enough to change anything. Hema Malini wore the khaki in <em>Andhaa Kaanoon</em> (1983). Rekha headlined <em>Phool Bane Angaray</em> (1991), playing an officer transformed from grieving widow into seeker of justice. In the South, Vijayashanti built something more sustained in Telugu cinema through the late 1980s and 1990s — an action-heroine identity that earned her the nickname "Lady Amitabh." Tabu turned the investigating officer into a morally complicated figure in the <em>Drishyam</em> franchise; Priyanka Chopra Jonas played a district superintendent in <em>Jai Gangaajal</em> (2016). Each portrayal was remarkable; each remained an island.</p>
<p>The reason was economic. Indian cinema's formula was organised around a simple equation: audiences came for the male star. From Amitabh Bachchan in <em>Zanjeer</em> to Ajay Devgn in <em>Singham</em>, the cop was imagined as a masculine force imposing order through brute strength. "What ends up happening," says <em>Brown</em> director Abhinay Deo, "is that even if a woman-centric film does well, there is no comparison to a man-centric film doing well. We're talking about ticket sales and the film scenario, until OTT came along."</p>
<h2>The OTT cascade</h2>
<p>The advent of Netflix in India in 2016, followed by JioHotstar, ZEE5, SonyLIV and Prime Video, changed the economic models that had limited storytelling to familiar tropes. "Prime time has changed to my time, and OTT has brought about that change," says Devendra Deshpande, CEO of Friday Filmworks. "The minute you free yourself from that chained scenario and say, 'I don't have to worry about box office anymore', it opens doors and windows."</p>
<p><em>Delhi Crime</em> was the proof of concept. Shefali Shah's calm, razor-sharp DCP Vartika Chaturvedi won India its first International Emmy for Best Drama Series in 2020; a third season streamed in November 2025, and the show became the most-watched in 10 countries on Netflix. "Even today, when I wear that uniform, I get goosebumps," Shah says. "Every single time I wear it, I stand differently."</p>
<blockquote class="pull-quote"><p>"Even today, when I wear that uniform, I get goosebumps. Every single time I wear it, I stand differently."</p><cite>— Shefali Shah, on playing DCP Vartika Chaturvedi in <em>Delhi Crime</em></cite></blockquote>
<p>The cascade that followed was quick. Sonakshi Sinha's Anjali Bhaati in <em>Dahaad</em> placed a small-town Rajasthani officer at the centre of a serial-killer investigation tangled with caste, gender and institutional prejudice. Raveena Tandon's Kasturi Dogra navigated a murder mystery in <em>Aranyak</em> while juggling family pressures and workplace scepticism. Bhumi Pednekkar's Rita Ferreira in <em>Daldal</em> brought a morally conflicted protagonist to the screen; Mona Singh's Baljit Kaur gave Punjabi crime drama its most textured female lead in <em>Kohrra</em>; Kareena Kapoor Khan's Jasmeet Kaur Bedi carried a cold-case investigation in England in <em>The Buckingham Murders</em>; Deepika Padukone entered Rohit Shetty's cop universe as Shakti Shetty in <em>Singham Again</em>. In June 2026, Karisma Kapoor returned in <em>Brown</em> as Rita Brown, a recovering alcoholic detective with the Kolkata police — flawed, unglamorous, fiercely complex.</p>
<h2>Vulnerability as the point</h2>
<p>What connects these women is a proposition once foreign to Indian mainstream storytelling: their vulnerability and competence coexist. "Portraying authority on screen isn't about volume or aggression. It's about stillness, conviction and knowing exactly when to push and when to hold back," Sinha says of Anjali Bhaati. "Perfection is no longer interesting. With Anjali, her flaws and vulnerabilities don't take away from her strength, they define it."</p>
<p>Rasika Dugal, who plays ACP Neeti Singh in <em>Delhi Crime</em>, extends the point: "There can be a lot of power with a soft exterior as well." Her character is petite, softly spoken and consistently underestimated — a deliberate rejection of the idea that women in control must behave in a masculine fashion.</p>
<h2>Impact and analysis</h2>
<p>The creative change had to survive the commercial one, and <em>Mardaani 3</em> is the strongest evidence it did. When the first film released in 2014, Mukerji's Shivani Roy was a rarity — a mainstream Hindi action heroine, neither young nor glamorous, carrying the film's moral and commercial weight alone. The franchise survived a six-year gap between instalments and returned in 2026 to its best numbers yet. The remaining fault line runs between platforms: digital has embraced female-first narratives, while theatrical box-office pressure still decides whether the industry's faith holds.</p>
<h2>Diaspora angle</h2>
<p>Streaming has made these performances global by default: <em>Delhi Crime</em> topped charts in 10 countries, and NRI audiences have discovered Indian crime drama on the same platforms that carry their Bollywood tentpoles.</p>
<h2>What's next</h2>
<p>Rohit Shetty has confirmed a standalone film for Deepika Padukone's Lady Singham, and Kareena Kapoor Khan's <em>Daayra</em> will test whether the theatrical audience for women-led crime stories keeps growing.</p>
"""

for aid, body in patches.items():
    resp = curl("PATCH", "p2_articles", data={"body": body, "word_count": wc(body)}, params=f"?id=eq.{aid}")
    r = json.loads(resp)
    print(json.dumps({"id": aid, "word_count": wc(body), "ok": bool(r)}))
